<a href="https://colab.research.google.com/github/faguirre3521-arch/Entrega-1/blob/main/Entrega%205/nulos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import altair as alt
import os

alt.data_transformers.disable_max_rows()

DataTransformerRegistry.enable('default')

In [ ]:
base = pd.read_csv("/content/Base de Datos Elecciones y Candidatos csv.csv", sep=';')
nacional = pd.read_csv("resumen_nacional_limpio.csv", sep=';')
opciones = pd.read_csv("opciones_nacional_limpio.csv", sep=';')

In [ ]:
display(base.head())
display(nacional.head())
display(opciones.head())

print("base:", base.shape)
print("nacional:", nacional.shape)
print("opciones:", opciones.shape)

,Candidatos,Año,Tarapacá,Arica y Parinacota,Antofagasta,Atacama,Coquimbo,Valparaíso,RM,O´Higgins,...,Ñuble,Biobío,Araucanía,Los Ríos,Los Lagos,Aysén,Magallanes,Total,Blancos de la votación,Nulos de la votación
0,Hernán Buchi,1989.0,52293,NaN,52023,33856,75795,219152,874649,109155,...,NaN,223677,112964,NaN,137360,11556,23941,2052116.0,75237.0,103631.0
1,Francisco Errazuriz,1989.0,31224,NaN,36710,10094,30020,139505,350210,43072,...,NaN,168792,95654,NaN,94466,5319,8162,1077172.0,NaN,NaN
2,Patricio Aylwin,1989.0,82387,NaN,120679,67803,141318,398096,1569524,215945,...,NaN,505439,186200,NaN,242071,20390,48910,3850571.0,NaN,NaN
3,Manfred Neff,1993.0,7472,NaN,13476,5230,10129,44954,176288,16787,...,NaN,55454,14516,NaN,22088,1406,4131,774742.0,273900.0,542778.0
4,Eugenio Pizarro,1993.0,9985,NaN,14966,10037,16673,35203,127042,17718,...,NaN,43163,12244,NaN,18210,1870,2916,654808.0,NaN,NaN

,eleccion_id,anio,vuelta,tipo,votos_candidaturas,nulos_total,blancos_total,factor_duplicacion_detectado,votos_emitidos,nulos_blancos_total,pct_nulos,pct_blancos,pct_nulos_blancos
0,1989_1,1989,1,Primera vuelta,6979859,103631,75237,1,7158727,178868,1.447618,1.050983,2.498601
1,1993_1,1993,1,Primera vuelta,6974947,271389,136950,2,7383286,408339,3.675721,1.854865,5.530586
2,1999_1,1999,1,Primera vuelta,7055116,159465,56991,2,7271572,216456,2.192992,0.783751,2.976743
3,1999_2,1999,2,Segunda vuelta,7178727,103351,44675,1,7326753,148026,1.410598,0.609752,2.020349
4,2005_1,2005,1,Primera vuelta,6942041,180485,84752,1,7207278,265237,2.504205,1.175922,3.680127

,eleccion_id,anio,vuelta,tipo,opcion,categoria,votos,votos_emitidos,porcentaje_emitidos
0,1989_1,1989,1,Primera vuelta,Francisco Errazuriz,Candidatura,1077172,7158727,15.046977
1,1989_1,1989,1,Primera vuelta,Hernán Buchi,Candidatura,2052116,7158727,28.665935
2,1989_1,1989,1,Primera vuelta,Patricio Aylwin,Candidatura,3850571,7158727,53.788488
3,1989_1,1989,1,Primera vuelta,Blancos,Voto que no elige,75237,7158727,1.050983
4,1989_1,1989,1,Primera vuelta,Nulos,Voto que no elige,103631,7158727,1.447618

base: (69, 21)
nacional: (16, 13)
opciones: (101, 9)

In [ ]:
print("COLUMNAS BASE")
print(base.columns.tolist())

print("\nCOLUMNAS NACIONAL")
print(nacional.columns.tolist())

print("\nCOLUMNAS OPCIONES")
print(opciones.columns.tolist())

COLUMNAS BASE
['Candidatos', 'Año', 'Tarapacá', 'Arica y Parinacota', 'Antofagasta', 'Atacama', 'Coquimbo', 'Valparaíso', 'RM', 'O´Higgins', 'Maule', 'Ñuble', 'Biobío', 'Araucanía', 'Los Ríos ', 'Los Lagos', 'Aysén', 'Magallanes', 'Total ', 'Blancos de la votación', 'Nulos de la votación']

COLUMNAS NACIONAL
['eleccion_id', 'anio', 'vuelta', 'tipo', 'votos_candidaturas', 'nulos_total', 'blancos_total', 'factor_duplicacion_detectado', 'votos_emitidos', 'nulos_blancos_total', 'pct_nulos', 'pct_blancos', 'pct_nulos_blancos']

COLUMNAS OPCIONES
['eleccion_id', 'anio', 'vuelta', 'tipo', 'opcion', 'categoria', 'votos', 'votos_emitidos', 'porcentaje_emitidos']

In [ ]:
display(
    nacional[
        [
            "eleccion_id",
            "anio",
            "vuelta",
            "tipo",
            "votos_candidaturas",
            "nulos_total",
            "blancos_total",
            "votos_emitidos",
            "nulos_blancos_total",
            "pct_nulos_blancos"
        ]
    ]
)

,eleccion_id,anio,vuelta,tipo,votos_candidaturas,nulos_total,blancos_total,votos_emitidos,nulos_blancos_total,pct_nulos_blancos
0,1989_1,1989,1,Primera vuelta,6979859,103631,75237,7158727,178868,2.498601
1,1993_1,1993,1,Primera vuelta,6974947,271389,136950,7383286,408339,5.530586
2,1999_1,1999,1,Primera vuelta,7055116,159465,56991,7271572,216456,2.976743
3,1999_2,1999,2,Segunda vuelta,7178727,103351,44675,7326753,148026,2.020349
4,2005_1,2005,1,Primera vuelta,6942041,180485,84752,7207278,265237,3.680127
5,2005_2,2005,2,Segunda vuelta,6959413,154972,47960,7162345,202932,2.833318
6,2009_1,2009,1,Primera vuelta,6977544,200420,86172,7264136,286592,3.945301
7,2009_2,2009,2,Segunda vuelta,6958972,189490,54909,7203371,244399,3.392842
8,2013_1,2013,1,Primera vuelta,6585808,66935,46268,6699011,113203,1.689846
9,2013_2,2013,2,Segunda vuelta,5582270,82916,32565,5697751,115481,2.026782
10,2017_1,2017,1,Primera vuelta,6600280,64504,38543,6703327,103047,1.537252
11,2017_2,2017,2,Segunda vuelta,6957546,56440,18892,7032878,75332,1.071140
12,2021_1,2021,1,Primera vuelta,6994533,55480,30493,7080506,85973,1.214221
13,2021_2,2021,2,Segunda vuelta,8237185,68616,23972,8329773,92588,1.111531
14,2025_1,2025,1,Primera vuelta,12911241,361403,141989,13414633,503392,3.752559
15,2025_2,2025,2,Segunda vuelta,12427608,783816,165344,13376768,949160,7.095585

In [ ]:
display(
    nacional[
        [
            "eleccion_id",
            "anio",
            "vuelta",
            "tipo",
            "votos_candidaturas",
            "nulos_total",
            "blancos_total",
            "votos_emitidos",
            "nulos_blancos_total",
            "pct_nulos_blancos"
        ]
    ]
)

,eleccion_id,anio,vuelta,tipo,votos_candidaturas,nulos_total,blancos_total,votos_emitidos,nulos_blancos_total,pct_nulos_blancos
0,1989_1,1989,1,Primera vuelta,6979859,103631,75237,7158727,178868,2.498601
1,1993_1,1993,1,Primera vuelta,6974947,271389,136950,7383286,408339,5.530586
2,1999_1,1999,1,Primera vuelta,7055116,159465,56991,7271572,216456,2.976743
3,1999_2,1999,2,Segunda vuelta,7178727,103351,44675,7326753,148026,2.020349
4,2005_1,2005,1,Primera vuelta,6942041,180485,84752,7207278,265237,3.680127
5,2005_2,2005,2,Segunda vuelta,6959413,154972,47960,7162345,202932,2.833318
6,2009_1,2009,1,Primera vuelta,6977544,200420,86172,7264136,286592,3.945301
7,2009_2,2009,2,Segunda vuelta,6958972,189490,54909,7203371,244399,3.392842
8,2013_1,2013,1,Primera vuelta,6585808,66935,46268,6699011,113203,1.689846
9,2013_2,2013,2,Segunda vuelta,5582270,82916,32565,5697751,115481,2.026782
10,2017_1,2017,1,Primera vuelta,6600280,64504,38543,6703327,103047,1.537252
11,2017_2,2017,2,Segunda vuelta,6957546,56440,18892,7032878,75332,1.071140
12,2021_1,2021,1,Primera vuelta,6994533,55480,30493,7080506,85973,1.214221
13,2021_2,2021,2,Segunda vuelta,8237185,68616,23972,8329773,92588,1.111531
14,2025_1,2025,1,Primera vuelta,12911241,361403,141989,13414633,503392,3.752559
15,2025_2,2025,2,Segunda vuelta,12427608,783816,165344,13376768,949160,7.095585

In [ ]:
nacional_grafico = nacional.copy()

nacional_grafico["anio"] = pd.to_numeric(nacional_grafico["anio"], errors="coerce")
nacional_grafico["vuelta"] = pd.to_numeric(nacional_grafico["vuelta"], errors="coerce")
nacional_grafico["pct_nulos_blancos"] = pd.to_numeric(nacional_grafico["pct_nulos_blancos"], errors="coerce")

nacional_grafico["vuelta_label"] = nacional_grafico["vuelta"].map({
    1: "Primera vuelta",
    2: "Segunda vuelta"
})

nacional_grafico = nacional_grafico.dropna(subset=["anio", "vuelta", "pct_nulos_blancos", "vuelta_label"])
nacional_grafico = nacional_grafico.sort_values(["vuelta", "anio"])

grafico_1 = alt.Chart(nacional_grafico).mark_line(
    point=True,
    strokeWidth=3
).encode(
    x=alt.X(
        "anio:Q",
        title="Año",
        scale=alt.Scale(domain=[1989, 2025]),
        axis=alt.Axis(
            values=[1989, 1993, 1999, 2005, 2009, 2013, 2017, 2021, 2025],
            format="d",
            labelAngle=0
        )
    ),
    y=alt.Y(
        "pct_nulos_blancos:Q",
        title="% nulos + blancos",
        axis=alt.Axis(format=".1f")
    ),
    color=alt.Color(
        "vuelta_label:N",
        title=None,
        scale=alt.Scale(
            domain=["Primera vuelta", "Segunda vuelta"],
            range=["#64748b", "#d94841"]
        )
    ),
    detail="vuelta_label:N",
    tooltip=[
        alt.Tooltip("anio:Q", title="Año", format="d"),
        alt.Tooltip("vuelta_label:N", title="Vuelta"),
        alt.Tooltip("pct_nulos_blancos:Q", title="% nulos + blancos", format=".2f"),
        alt.Tooltip("nulos_blancos_total:Q", title="Nulos + blancos", format=","),
        alt.Tooltip("votos_emitidos:Q", title="Votos emitidos", format=",")
    ]
).properties(
    title={
        "text": "El voto que no elige se mantiene acotado, pero cambia con el contexto",
        "subtitle": "Porcentaje de votos nulos y blancos sobre votos emitidos en elecciones presidenciales chilenas, 1989–2025",
        "anchor": "start",
        "fontSize": 18,
        "subtitleFontSize": 12,
        "subtitleColor": "#374151"
    },
    width=820,
    height=420
).configure_view(
    strokeWidth=0
).configure_axis(
    gridColor="#e5e7eb",
    labelFontSize=11,
    titleFontSize=12
).configure_legend(
    orient="top",
    title=None
)

grafico_1

alt.Chart(...)

In [ ]:
!pip install vl-convert-python
grafico_1.save("01_evolucion_nacional_nulos_blancos.html")
grafico_1.save("01_evolucion_nacional_nulos_blancos.png", scale_factor=2)

Collecting vl-convert-python
  Downloading vl_convert_python-1.9.0.post1-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.1 kB)
Downloading vl_convert_python-1.9.0.post1-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (33.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.5/33.5 MB 64.4 MB/s eta 0:00:00
Installing collected packages: vl-convert-python
Successfully installed vl-convert-python-1.9.0.post1

In [ ]:
comparacion_vueltas = nacional_grafico.copy()

tabla_salto = comparacion_vueltas.pivot_table(
    index="anio",
    columns="vuelta",
    values="pct_nulos_blancos",
    aggfunc="first"
).reset_index()

tabla_salto = tabla_salto.rename(columns={
    1: "primera_vuelta",
    2: "segunda_vuelta"
})

tabla_salto = tabla_salto.dropna(subset=["primera_vuelta", "segunda_vuelta"])

tabla_salto["diferencia_pp"] = tabla_salto["segunda_vuelta"] - tabla_salto["primera_vuelta"]

tabla_salto["direccion"] = np.where(
    tabla_salto["diferencia_pp"] >= 0,
    "Sube en segunda vuelta",
    "Baja en segunda vuelta"
)

display(tabla_salto)

vuelta,anio,primera_vuelta,segunda_vuelta,diferencia_pp,direccion
2,1999,2.976743,2.020349,-0.956394,Baja en segunda vuelta
3,2005,3.680127,2.833318,-0.846809,Baja en segunda vuelta
4,2009,3.945301,3.392842,-0.552459,Baja en segunda vuelta
5,2013,1.689846,2.026782,0.336936,Sube en segunda vuelta
6,2017,1.537252,1.071140,-0.466111,Baja en segunda vuelta
7,2021,1.214221,1.111531,-0.102690,Baja en segunda vuelta
8,2025,3.752559,7.095585,3.343027,Sube en segunda vuelta

In [ ]:
grafico_2 = alt.Chart(tabla_salto).mark_bar(
    cornerRadiusEnd=4
).encode(
    x=alt.X(
        "anio:O",
        title="Año",
        axis=alt.Axis(labelAngle=0)
    ),
    y=alt.Y(
        "diferencia_pp:Q",
        title="Diferencia en puntos porcentuales",
        axis=alt.Axis(format="+.1f")
    ),
    color=alt.Color(
        "direccion:N",
        title=None,
        scale=alt.Scale(
            domain=["Sube en segunda vuelta", "Baja en segunda vuelta"],
            range=["#d94841", "#64748b"]
        )
    ),
    tooltip=[
        alt.Tooltip("anio:O", title="Año"),
        alt.Tooltip("primera_vuelta:Q", title="Primera vuelta", format=".2f"),
        alt.Tooltip("segunda_vuelta:Q", title="Segunda vuelta", format=".2f"),
        alt.Tooltip("diferencia_pp:Q", title="Diferencia pp", format="+.2f")
    ]
).properties(
    title={
        "text": "La segunda vuelta no siempre empuja el voto nulo y blanco hacia arriba",
        "subtitle": "Diferencia en puntos porcentuales entre primera y segunda vuelta presidencial",
        "anchor": "start",
        "fontSize": 18,
        "subtitleFontSize": 12,
        "subtitleColor": "#374151"
    },
    width=720,
    height=380
).configure_view(
    strokeWidth=0
).configure_axis(
    gridColor="#e5e7eb",
    labelFontSize=11,
    titleFontSize=12
).configure_legend(
    orient="top",
    title=None
)

grafico_2

alt.Chart(...)

In [ ]:
grafico_2.save("02_diferencia_primera_segunda_vuelta.html")
grafico_2.save("02_diferencia_primera_segunda_vuelta.png", scale_factor=2)

In [ ]:
sistema = nacional_grafico.copy()

sistema["sistema_voto"] = np.select(
    [
        sistema["anio"].between(1989, 2009),
        sistema["anio"].between(2013, 2021),
        sistema["anio"] >= 2025
    ],
    [
        "Inscripción voluntaria y voto obligatorio",
        "Inscripción automática y voto voluntario",
        "Inscripción automática y voto obligatorio"
    ],
    default="Otro"
)

display(
    sistema[[
        "anio",
        "vuelta",
        "vuelta_label",
        "sistema_voto",
        "pct_nulos_blancos"
    ]]
)

,anio,vuelta,vuelta_label,sistema_voto,pct_nulos_blancos
0,1989,1,Primera vuelta,Inscripción voluntaria y voto obligatorio,2.498601
1,1993,1,Primera vuelta,Inscripción voluntaria y voto obligatorio,5.530586
2,1999,1,Primera vuelta,Inscripción voluntaria y voto obligatorio,2.976743
4,2005,1,Primera vuelta,Inscripción voluntaria y voto obligatorio,3.680127
6,2009,1,Primera vuelta,Inscripción voluntaria y voto obligatorio,3.945301
8,2013,1,Primera vuelta,Inscripción automática y voto voluntario,1.689846
10,2017,1,Primera vuelta,Inscripción automática y voto voluntario,1.537252
12,2021,1,Primera vuelta,Inscripción automática y voto voluntario,1.214221
14,2025,1,Primera vuelta,Inscripción automática y voto obligatorio,3.752559
3,1999,2,Segunda vuelta,Inscripción voluntaria y voto obligatorio,2.020349
5,2005,2,Segunda vuelta,Inscripción voluntaria y voto obligatorio,2.833318
7,2009,2,Segunda vuelta,Inscripción voluntaria y voto obligatorio,3.392842
9,2013,2,Segunda vuelta,Inscripción automática y voto voluntario,2.026782
11,2017,2,Segunda vuelta,Inscripción automática y voto voluntario,1.071140
13,2021,2,Segunda vuelta,Inscripción automática y voto voluntario,1.111531
15,2025,2,Segunda vuelta,Inscripción automática y voto obligatorio,7.095585

In [ ]:
periodos = pd.DataFrame({
    "inicio": [2013],
    "fin": [2021],
    "periodo": ["Voto voluntario"]
})

In [ ]:
linea_sistema = alt.Chart(sistema).mark_line(
    point=True,
    strokeWidth=3
).encode(
    x=alt.X(
        "anio:Q",
        title="Año",
        scale=alt.Scale(domain=[1989, 2025]),
        axis=alt.Axis(
            values=[1989, 1993, 1999, 2005, 2009, 2013, 2017, 2021, 2025],
            format="d",
            labelAngle=0
        )
    ),
    y=alt.Y(
        "pct_nulos_blancos:Q",
        title="% nulos + blancos",
        axis=alt.Axis(format=".1f")
    ),
    color=alt.Color(
        "vuelta_label:N",
        title=None,
        scale=alt.Scale(
            domain=["Primera vuelta", "Segunda vuelta"],
            range=["#64748b", "#d94841"]
        )
    ),
    detail="vuelta_label:N",
    tooltip=[
        alt.Tooltip("anio:Q", title="Año", format="d"),
        alt.Tooltip("vuelta_label:N", title="Vuelta"),
        alt.Tooltip("sistema_voto:N", title="Sistema de voto"),
        alt.Tooltip("pct_nulos_blancos:Q", title="% nulos + blancos", format=".2f")
    ]
)

marcas_periodo = pd.DataFrame({
    "anio": [2013, 2021, 2025],
    "evento": [
        "Inicio inscripción automática + voto voluntario",
        "Última presidencial con voto voluntario",
        "Retorno del voto obligatorio en presidencial"
    ]
})

reglas_periodo = alt.Chart(marcas_periodo).mark_rule(
    strokeDash=[5, 5],
    color="#f59e0b",
    strokeWidth=2
).encode(
    x=alt.X("anio:Q"),
    tooltip=[
        alt.Tooltip("anio:Q", title="Año", format="d"),
        alt.Tooltip("evento:N", title="Cambio")
    ]
)

texto_periodo = alt.Chart(pd.DataFrame({
    "anio": [2017],
    "valor": [sistema["pct_nulos_blancos"].max() * 0.88],
    "texto": ["Voto voluntario"]
})).mark_text(
    fontSize=12,
    fontWeight="bold",
    color="#92400e"
).encode(
    x=alt.X("anio:Q"),
    y=alt.Y("valor:Q"),
    text="texto:N"
)

texto_2025 = alt.Chart(pd.DataFrame({
    "anio": [2025],
    "valor": [sistema["pct_nulos_blancos"].max() * 0.78],
    "texto": ["Retorno obligatorio"]
})).mark_text(
    align="right",
    dx=-6,
    fontSize=12,
    fontWeight="bold",
    color="#92400e"
).encode(
    x=alt.X("anio:Q"),
    y=alt.Y("valor:Q"),
    text="texto:N"
)

grafico_3 = (linea_sistema + reglas_periodo + texto_periodo + texto_2025).properties(
    title={
        "text": "El sistema electoral cambia la lectura del voto nulo y blanco",
        "subtitle": "1989–2009: voto obligatorio para inscritos; 2013–2021: voto voluntario; 2025: retorno del voto obligatorio con inscripción automática",
        "anchor": "start",
        "fontSize": 18,
        "subtitleFontSize": 12,
        "subtitleColor": "#374151"
    },
    width=820,
    height=420
).configure_view(
    strokeWidth=0
).configure_axis(
    gridColor="#e5e7eb",
    labelFontSize=11,
    titleFontSize=12
).configure_legend(
    orient="top",
    title=None
)

grafico_3

alt.LayerChart(...)

In [85]:
import os
import pandas as pd
import altair as alt

os.makedirs("graficos_html", exist_ok=True)

sistema = nacional.copy()

sistema["anio"] = pd.to_numeric(sistema["anio"], errors="coerce")
sistema["pct_nulos_blancos"] = pd.to_numeric(sistema["pct_nulos_blancos"], errors="coerce")

sistema["vuelta_label"] = sistema["vuelta"].map({
    1: "Primera vuelta",
    2: "Segunda vuelta"
})

sistema["sistema_voto"] = sistema["anio"].apply(
    lambda x: "Obligatorio para inscritos" if x <= 2009
    else "Voluntario" if x <= 2021
    else "Obligatorio con inscripción automática"
)

linea_sistema = alt.Chart(sistema).mark_line(
    point=True,
    strokeWidth=3
).encode(
    x=alt.X(
        "anio:Q",
        title="Año",
        scale=alt.Scale(domain=[1989, 2025]),
        axis=alt.Axis(
            values=[1989, 1993, 1999, 2005, 2009, 2013, 2017, 2021, 2025],
            format="d",
            labelAngle=0
        )
    ),
    y=alt.Y(
        "pct_nulos_blancos:Q",
        title="% nulos + blancos",
        axis=alt.Axis(format=".1f")
    ),
    color=alt.Color(
        "vuelta_label:N",
        title=None,
        scale=alt.Scale(
            domain=["Primera vuelta", "Segunda vuelta"],
            range=["#64748b", "#d94841"]
        )
    ),
    detail="vuelta_label:N",
    tooltip=[
        alt.Tooltip("anio:Q", title="Año", format="d"),
        alt.Tooltip("vuelta_label:N", title="Vuelta"),
        alt.Tooltip("sistema_voto:N", title="Sistema de voto"),
        alt.Tooltip("pct_nulos_blancos:Q", title="% nulos + blancos", format=".2f")
    ]
)

marcas_periodo = pd.DataFrame({
    "anio": [2013, 2021, 2025],
    "evento": [
        "Inicio inscripción automática + voto voluntario",
        "Última presidencial con voto voluntario",
        "Retorno del voto obligatorio en presidencial"
    ]
})

reglas_periodo = alt.Chart(marcas_periodo).mark_rule(
    strokeDash=[5, 5],
    color="#f59e0b",
    strokeWidth=2
).encode(
    x=alt.X("anio:Q"),
    tooltip=[
        alt.Tooltip("anio:Q", title="Año", format="d"),
        alt.Tooltip("evento:N", title="Cambio")
    ]
)

texto_periodo = alt.Chart(pd.DataFrame({
    "anio": [2017],
    "valor": [sistema["pct_nulos_blancos"].max() * 0.88],
    "texto": ["Voto voluntario"]
})).mark_text(
    fontSize=12,
    fontWeight="bold",
    color="#92400e"
).encode(
    x=alt.X("anio:Q"),
    y=alt.Y("valor:Q"),
    text="texto:N"
)

texto_2025 = alt.Chart(pd.DataFrame({
    "anio": [2025],
    "valor": [sistema["pct_nulos_blancos"].max() * 0.78],
    "texto": ["Retorno obligatorio"]
})).mark_text(
    align="right",
    dx=-6,
    fontSize=12,
    fontWeight="bold",
    color="#92400e"
).encode(
    x=alt.X("anio:Q"),
    y=alt.Y("valor:Q"),
    text="texto:N"
)

grafico_3 = (linea_sistema + reglas_periodo + texto_periodo + texto_2025).properties(
    title={
        "text": "El sistema electoral cambia la lectura del voto nulo y blanco",
        "subtitle": "1989–2009: voto obligatorio para inscritos; 2013–2021: voto voluntario; 2025: retorno del voto obligatorio con inscripción automática",
        "anchor": "start",
        "fontSize": 18,
        "subtitleFontSize": 12,
        "subtitleColor": "#374151"
    },
    width=820,
    height=420
).configure_view(
    strokeWidth=0
).configure_axis(
    gridColor="#e5e7eb",
    labelFontSize=11,
    titleFontSize=12
).configure_legend(
    orient="top",
    title=None
)

grafico_3.save("graficos_html/03_sistema_electoral_nulos_blancos.html")

print("Listo: 03_sistema_electoral_nulos_blancos.html creado en graficos_html")

Listo: 03_sistema_electoral_nulos_blancos.html creado en graficos_html

In [ ]:
grafico_3.save("03_sistema_voto_obligatorio_voluntario.html")
grafico_3.save("03_sistema_voto_obligatorio_voluntario.png", scale_factor=2)

In [ ]:
print(nacional.columns.tolist())

['eleccion_id', 'anio', 'vuelta', 'tipo', 'votos_candidaturas', 'nulos_total', 'blancos_total', 'factor_duplicacion_detectado', 'votos_emitidos', 'nulos_blancos_total', 'pct_nulos', 'pct_blancos', 'pct_nulos_blancos']

In [ ]:
polarizacion = pd.read_csv("polarizacion_elecciones_chile_1989_2025.csv")

polarizacion.columns = polarizacion.columns.str.strip()

display(polarizacion.head())
print(polarizacion.columns.tolist())

,Año,Vuelta,Candidato,Partido,Coalición,Polarización vuelta 1,Polarización vuelta 2,Polarización total
0,1989,0,Hernán Büchi,Independiente,Democracia y Progreso,NaN,NaN,3.0
1,1989,0,Francisco Errázuriz,Independiente,Independiente,NaN,NaN,NaN
2,1989,0,Patricio Aylwin,DC,Concertación,NaN,NaN,NaN
3,1993,0,Manfred Max-Neef,Movimiento Ecologista,X,NaN,NaN,2.0
4,1993,0,Eugenio Pizarro,Independiente,Alternativa Democrática de Izquierda Allendista,NaN,NaN,NaN

['Año', 'Vuelta', 'Candidato', 'Partido', 'Coalición', 'Polarización vuelta 1', 'Polarización vuelta 2', 'Polarización total']

In [ ]:
polarizacion = polarizacion.rename(columns={
    "Año": "anio",
    "Vuelta": "vuelta",
    "Polarización vuelta 1": "polarizacion_v1",
    "Polarización vuelta 2": "polarizacion_v2",
    "Polarización total": "polarizacion_total",
    "Polarizacion vuelta 1": "polarizacion_v1",
    "Polarizacion vuelta 2": "polarizacion_v2",
    "Polarizacion total": "polarizacion_total"
})

polarizacion.columns = polarizacion.columns.str.strip()

display(polarizacion.head())
print(polarizacion.columns.tolist())

,anio,vuelta,Candidato,Partido,Coalición,polarizacion_v1,polarizacion_v2,polarizacion_total
0,1989,0,Hernán Büchi,Independiente,Democracia y Progreso,NaN,NaN,3.0
1,1989,0,Francisco Errázuriz,Independiente,Independiente,NaN,NaN,NaN
2,1989,0,Patricio Aylwin,DC,Concertación,NaN,NaN,NaN
3,1993,0,Manfred Max-Neef,Movimiento Ecologista,X,NaN,NaN,2.0
4,1993,0,Eugenio Pizarro,Independiente,Alternativa Democrática de Izquierda Allendista,NaN,NaN,NaN

['anio', 'vuelta', 'Candidato', 'Partido', 'Coalición', 'polarizacion_v1', 'polarizacion_v2', 'polarizacion_total']

In [ ]:
for col in ["anio", "vuelta", "polarizacion_v1", "polarizacion_v2", "polarizacion_total"]:
    if col in polarizacion.columns:
        polarizacion[col] = (
            polarizacion[col]
            .astype(str)
            .str.replace(",", ".", regex=False)
            .replace("nan", np.nan)
        )
        polarizacion[col] = pd.to_numeric(polarizacion[col], errors="coerce")

display(polarizacion.head())

,anio,vuelta,Candidato,Partido,Coalición,polarizacion_v1,polarizacion_v2,polarizacion_total
0,1989,0,Hernán Büchi,Independiente,Democracia y Progreso,NaN,NaN,3.0
1,1989,0,Francisco Errázuriz,Independiente,Independiente,NaN,NaN,NaN
2,1989,0,Patricio Aylwin,DC,Concertación,NaN,NaN,NaN
3,1993,0,Manfred Max-Neef,Movimiento Ecologista,X,NaN,NaN,2.0
4,1993,0,Eugenio Pizarro,Independiente,Alternativa Democrática de Izquierda Allendista,NaN,NaN,NaN

In [ ]:
polarizacion_resumen = (
    polarizacion
    .groupby("anio", as_index=False)
    .agg(
        polarizacion_v1=("polarizacion_v1", "max"),
        polarizacion_v2=("polarizacion_v2", "max"),
        polarizacion_total=("polarizacion_total", "max")
    )
)

display(polarizacion_resumen)

   anio  polarizacion_v1  polarizacion_v2  polarizacion_total
0  1989              NaN              NaN                 3.0
1  1993              NaN              NaN                 2.0
2  1999              3.0              3.0                 3.0
3  2005              3.0              3.0                 3.0
4  2009              3.0              2.0                 2.5
5  2013              3.0              3.0                 3.0
6  2017              4.0              3.0                 3.5
7  2021              4.0              5.0                 4.5
8  2025              4.0              5.0                 4.5

In [ ]:
polarizacion_grafico = polarizacion_resumen.copy()

polarizacion_grafico = polarizacion_grafico.sort_values("anio")

polarizacion_larga = polarizacion_grafico.melt(
    id_vars="anio",
    value_vars=["polarizacion_v1", "polarizacion_v2"],
    var_name="vuelta_tipo",
    value_name="polarizacion"
)

polarizacion_larga["vuelta_label"] = polarizacion_larga["vuelta_tipo"].map({
    "polarizacion_v1": "Primera vuelta",
    "polarizacion_v2": "Segunda vuelta"
})

polarizacion_larga = polarizacion_larga.dropna(subset=["polarizacion"])

display(polarizacion_larga)

    anio      vuelta_tipo  polarizacion    vuelta_label
2   1999  polarizacion_v1           3.0  Primera vuelta
3   2005  polarizacion_v1           3.0  Primera vuelta
4   2009  polarizacion_v1           3.0  Primera vuelta
5   2013  polarizacion_v1           3.0  Primera vuelta
6   2017  polarizacion_v1           4.0  Primera vuelta
7   2021  polarizacion_v1           4.0  Primera vuelta
8   2025  polarizacion_v1           4.0  Primera vuelta
11  1999  polarizacion_v2           3.0  Segunda vuelta
12  2005  polarizacion_v2           3.0  Segunda vuelta
13  2009  polarizacion_v2           2.0  Segunda vuelta
14  2013  polarizacion_v2           3.0  Segunda vuelta
15  2017  polarizacion_v2           3.0  Segunda vuelta
16  2021  polarizacion_v2           5.0  Segunda vuelta
17  2025  polarizacion_v2           5.0  Segunda vuelta

In [ ]:
grafico_5 = alt.Chart(polarizacion_larga).mark_bar(
    cornerRadiusEnd=4
).encode(
    x=alt.X(
        "anio:O",
        title="Año",
        axis=alt.Axis(labelAngle=0)
    ),
    y=alt.Y(
        "polarizacion:Q",
        title="Puntaje de polarización",
        scale=alt.Scale(domain=[0, 5])
    ),
    color=alt.Color(
        "vuelta_label:N",
        title=None,
        scale=alt.Scale(
            domain=["Primera vuelta", "Segunda vuelta"],
            range=["#64748b", "#d94841"]
        )
    ),
    xOffset=alt.XOffset("vuelta_label:N"),
    tooltip=[
        alt.Tooltip("anio:O", title="Año"),
        alt.Tooltip("vuelta_label:N", title="Vuelta"),
        alt.Tooltip("polarizacion:Q", title="Polarización", format=".1f")
    ]
).properties(
    title={
        "text": "La temperatura política sube en las últimas presidenciales",
        "subtitle": "Puntaje de polarización de la oferta presidencial por primera y segunda vuelta",
        "anchor": "start",
        "fontSize": 18,
        "subtitleFontSize": 12,
        "subtitleColor": "#374151"
    },
    width=760,
    height=400
).configure_view(
    strokeWidth=0
).configure_axis(
    gridColor="#e5e7eb",
    labelFontSize=11,
    titleFontSize=12
).configure_legend(
    orient="top",
    title=None
)

grafico_5

alt.Chart(...)

In [ ]:
grafico_5.save("05_polarizacion_oferta_presidencial.html")
grafico_5.save("05_polarizacion_oferta_presidencial.png", scale_factor=2)

In [ ]:
polarizacion_cruce = pd.merge(
    nacional_grafico[['anio', 'vuelta_label', 'pct_nulos_blancos']],
    polarizacion_larga[['anio', 'vuelta_label', 'polarizacion']],
    on=['anio', 'vuelta_label'],
    how='outer'
)
cruce_linea = polarizacion_cruce.copy()

cruce_linea["pct_nulos_blancos_norm"] = (
    cruce_linea["pct_nulos_blancos"] / cruce_linea["pct_nulos_blancos"].max() * 5
)

cruce_linea_larga = cruce_linea.melt(
    id_vars=["anio", "vuelta_label"],
    value_vars=["polarizacion", "pct_nulos_blancos_norm"],
    var_name="variable",
    value_name="valor"
)

cruce_linea_larga["variable_label"] = cruce_linea_larga["variable"].map({
    "polarizacion": "Polarización",
    "pct_nulos_blancos_norm": "Nulos + blancos normalizados"
})

display(cruce_linea_larga)

,anio,vuelta_label,variable,valor,variable_label
0,1989,Primera vuelta,polarizacion,NaN,Polarización
1,1993,Primera vuelta,polarizacion,NaN,Polarización
2,1999,Primera vuelta,polarizacion,3.000000,Polarización
3,1999,Segunda vuelta,polarizacion,3.000000,Polarización
4,2005,Primera vuelta,polarizacion,3.000000,Polarización
5,2005,Segunda vuelta,polarizacion,3.000000,Polarización
6,2009,Primera vuelta,polarizacion,3.000000,Polarización
7,2009,Segunda vuelta,polarizacion,2.000000,Polarización
8,2013,Primera vuelta,polarizacion,3.000000,Polarización
9,2013,Segunda vuelta,polarizacion,3.000000,Polarización
10,2017,Primera vuelta,polarizacion,4.000000,Polarización
11,2017,Segunda vuelta,polarizacion,3.000000,Polarización
12,2021,Primera vuelta,polarizacion,4.000000,Polarización
13,2021,Segunda vuelta,polarizacion,5.000000,Polarización
14,2025,Primera vuelta,polarizacion,4.000000,Polarización
15,2025,Segunda vuelta,polarizacion,5.000000,Polarización
16,1989,Primera vuelta,pct_nulos_blancos_norm,1.760673,Nulos + blancos normalizados
17,1993,Primera vuelta,pct_nulos_blancos_norm,3.897202,Nulos + blancos normalizados
18,1999,Primera vuelta,pct_nulos_blancos_norm,2.097602,Nulos + blancos normalizados
19,1999,Segunda vuelta,pct_nulos_blancos_norm,1.423666,Nulos + blancos normalizados
20,2005,Primera vuelta,pct_nulos_blancos_norm,2.593251,Nulos + blancos normalizados
21,2005,Segunda vuelta,pct_nulos_blancos_norm,1.996536,Nulos + blancos normalizados
22,2009,Primera vuelta,pct_nulos_blancos_norm,2.780109,Nulos + blancos normalizados
23,2009,Segunda vuelta,pct_nulos_blancos_norm,2.390812,Nulos + blancos normalizados
24,2013,Primera vuelta,pct_nulos_blancos_norm,1.190773,Nulos + blancos normalizados
25,2013,Segunda vuelta,pct_nulos_blancos_norm,1.428199,Nulos + blancos normalizados
26,2017,Primera vuelta,pct_nulos_blancos_norm,1.083245,Nulos + blancos normalizados
27,2017,Segunda vuelta,pct_nulos_blancos_norm,0.754794,Nulos + blancos normalizados
28,2021,Primera vuelta,pct_nulos_blancos_norm,0.855617,Nulos + blancos normalizados
29,2021,Segunda vuelta,pct_nulos_blancos_norm,0.783255,Nulos + blancos normalizados
30,2025,Primera vuelta,pct_nulos_blancos_norm,2.644291,Nulos + blancos normalizados
31,2025,Segunda vuelta,pct_nulos_blancos_norm,5.000000,Nulos + blancos normalizados

In [ ]:
avance_anual = (
    nacional_grafico
    .groupby("anio", as_index=False)
    .agg(
        nulos_total=("nulos_total", "sum"),
        blancos_total=("blancos_total", "sum"),
        nulos_blancos_total=("nulos_blancos_total", "sum"),
        votos_emitidos=("votos_emitidos", "sum")
    )
)

avance_anual["pct_nulos"] = avance_anual["nulos_total"] / avance_anual["votos_emitidos"] * 100
avance_anual["pct_blancos"] = avance_anual["blancos_total"] / avance_anual["votos_emitidos"] * 100
avance_anual["pct_nulos_blancos"] = avance_anual["nulos_blancos_total"] / avance_anual["votos_emitidos"] * 100

avance_anual = avance_anual.sort_values("anio")

display(avance_anual)

,anio,nulos_total,blancos_total,nulos_blancos_total,votos_emitidos,pct_nulos,pct_blancos,pct_nulos_blancos
0,1989,103631,75237,178868,7158727,1.447618,1.050983,2.498601
1,1993,271389,136950,408339,7383286,3.675721,1.854865,5.530586
2,1999,262816,101666,364482,14598325,1.800316,0.696422,2.496738
3,2005,335457,132712,468169,14369623,2.334487,0.923559,3.258047
4,2009,389910,141081,530991,14467507,2.695074,0.975158,3.670232
5,2013,149851,78833,228684,12396762,1.208791,0.635916,1.844708
6,2017,120944,57435,178379,13736205,0.880476,0.418129,1.298605
7,2021,124096,54465,178561,15410279,0.805281,0.353433,1.158714
8,2025,1145219,307333,1452552,26791401,4.274577,1.147133,5.421710

In [ ]:
grafico_avance_anual = alt.Chart(avance_anual).mark_line(
    point=True,
    strokeWidth=3,
    color="#d94841"
).encode(
    x=alt.X(
        "anio:Q",
        title="Año",
        scale=alt.Scale(domain=[1989, 2025]),
        axis=alt.Axis(
            values=[1989, 1993, 1999, 2005, 2009, 2013, 2017, 2021, 2025],
            format="d",
            labelAngle=0
        )
    ),
    y=alt.Y(
        "pct_nulos_blancos:Q",
        title="% nulos + blancos",
        axis=alt.Axis(format=".1f")
    ),
    tooltip=[
        alt.Tooltip("anio:Q", title="Año", format="d"),
        alt.Tooltip("pct_nulos_blancos:Q", title="% nulos + blancos", format=".2f"),
        alt.Tooltip("nulos_total:Q", title="Nulos", format=","),
        alt.Tooltip("blancos_total:Q", title="Blancos", format=","),
        alt.Tooltip("votos_emitidos:Q", title="Votos emitidos", format=",")
    ]
).properties(
    title={
        "text": "El voto que no elige avanza con fuerza en 2025",
        "subtitle": "Porcentaje anual de votos nulos y blancos, juntando primera y segunda vuelta cuando corresponde",
        "anchor": "start",
        "fontSize": 18,
        "subtitleFontSize": 12,
        "subtitleColor": "#374151"
    },
    width=820,
    height=420
).configure_view(
    strokeWidth=0
).configure_axis(
    gridColor="#e5e7eb",
    labelFontSize=11,
    titleFontSize=12
)

grafico_avance_anual

alt.Chart(...)

In [ ]:
regional = pd.read_csv("base_regional_historica_1989_2025_revisada.csv")
display(regional.head())
print(regional.shape)

,eleccion_id,anio,vuelta,region_codigo,region,region_fuente,division_regional,nulos,blancos,nulos_blancos,votos_emitidos,pct_nulos_blancos,nota_limite_regional
0,1989_1,1989,1,1,Tarapacá,Tarapacá,13 regiones,2833,1739,4572,170476,2.681902,División regional histórica de 13 regiones: Ta...
1,1989_1,1989,1,2,Antofagasta,Antofagasta,13 regiones,3191,1980,5171,214583,2.409790,División regional histórica de 13 regiones: Ta...
2,1989_1,1989,1,3,Atacama,Atacama,13 regiones,1385,1501,2886,114639,2.517468,División regional histórica de 13 regiones: Ta...
3,1989_1,1989,1,4,Coquimbo,Coquimbo,13 regiones,3915,3881,7796,254929,3.058106,División regional histórica de 13 regiones: Ta...
4,1989_1,1989,1,5,Valparaíso,Valparaíso,13 regiones,10482,7478,17960,774713,2.318278,División regional histórica de 13 regiones: Ta...

(232, 13)

In [ ]:
regional = pd.read_csv("base_regional_historica_1989_2025_revisada.csv")

display(regional.head())
print(regional.shape)
print(regional.columns.tolist())

,eleccion_id,anio,vuelta,region_codigo,region,region_fuente,division_regional,nulos,blancos,nulos_blancos,votos_emitidos,pct_nulos_blancos,nota_limite_regional
0,1989_1,1989,1,1,Tarapacá,Tarapacá,13 regiones,2833,1739,4572,170476,2.681902,División regional histórica de 13 regiones: Ta...
1,1989_1,1989,1,2,Antofagasta,Antofagasta,13 regiones,3191,1980,5171,214583,2.409790,División regional histórica de 13 regiones: Ta...
2,1989_1,1989,1,3,Atacama,Atacama,13 regiones,1385,1501,2886,114639,2.517468,División regional histórica de 13 regiones: Ta...
3,1989_1,1989,1,4,Coquimbo,Coquimbo,13 regiones,3915,3881,7796,254929,3.058106,División regional histórica de 13 regiones: Ta...
4,1989_1,1989,1,5,Valparaíso,Valparaíso,13 regiones,10482,7478,17960,774713,2.318278,División regional histórica de 13 regiones: Ta...

(232, 13)
['eleccion_id', 'anio', 'vuelta', 'region_codigo', 'region', 'region_fuente', 'division_regional', 'nulos', 'blancos', 'nulos_blancos', 'votos_emitidos', 'pct_nulos_blancos', 'nota_limite_regional']

In [ ]:
regional_grafico = regional.copy()

regional_grafico["anio"] = pd.to_numeric(regional_grafico["anio"], errors="coerce")
regional_grafico["vuelta"] = pd.to_numeric(regional_grafico["vuelta"], errors="coerce")
regional_grafico["pct_nulos_blancos"] = pd.to_numeric(
    regional_grafico["pct_nulos_blancos"],
    errors="coerce"
)

regional_grafico["vuelta_label"] = regional_grafico["vuelta"].map({
    1: "Primera vuelta",
    2: "Segunda vuelta"
})

regional_grafico = regional_grafico.dropna(
    subset=["anio", "vuelta", "region", "pct_nulos_blancos"]
)

regional_grafico = regional_grafico.sort_values(["region", "vuelta", "anio"])

display(regional_grafico.head())
print(regional_grafico.shape)
print(regional_grafico["region"].nunique())
print(regional_grafico["region"].unique())

,eleccion_id,anio,vuelta,region_codigo,region,region_fuente,division_regional,nulos,blancos,nulos_blancos,votos_emitidos,pct_nulos_blancos,nota_limite_regional,vuelta_label
1,1989_1,1989,1,2,Antofagasta,Antofagasta,13 regiones,3191,1980,5171,214583,2.409790,División regional histórica de 13 regiones: Ta...,Primera vuelta
14,1993_1,1993,1,2,Antofagasta,Antofagasta,13 regiones,10375,3814,14189,216911,6.541393,División regional histórica de 13 regiones: Ta...,Primera vuelta
27,1999_1,1999,1,2,Antofagasta,DE ANTOFAGASTA,13 regiones,5835,1705,7540,206083,3.658720,División regional histórica de 13 regiones: Ta...,Primera vuelta
53,2005_1,2005,1,2,Antofagasta,DE ANTOFAGASTA,13 regiones,5705,2007,7712,202407,3.810145,División regional histórica de 13 regiones: Ta...,Primera vuelta
79,2009_1,2009,1,2,Antofagasta,DE ANTOFAGASTA,15 regiones,7259,2063,9322,198837,4.688262,División regional de 15 regiones: Biobío inclu...,Primera vuelta

(232, 14)
16
['Antofagasta' 'Arica y Parinacota' 'Atacama' 'Aysén' 'Biobío' 'Coquimbo'
 'La Araucanía' 'Los Lagos' 'Los Ríos' 'Magallanes' 'Maule'
 'Metropolitana' 'O’Higgins' 'Tarapacá' 'Valparaíso' 'Ñuble']

In [ ]:
grafico_regional = alt.Chart(regional_grafico, width=180, height=130).mark_line(
    point=True,
    strokeWidth=2
).encode(
    x=alt.X(
        "anio:Q",
        title="Año",
        scale=alt.Scale(domain=[1989, 2025]),
        axis=alt.Axis(
            values=[1989, 1993, 1999, 2005, 2009, 2013, 2017, 2021, 2025],
            format="d",
            labelAngle=0
        )
    ),
    y=alt.Y(
        "pct_nulos_blancos:Q",
        title="% nulos + blancos",
        axis=alt.Axis(format=".1f")
    ),
    color=alt.Color(
        "vuelta_label:N",
        title=None,
        scale=alt.Scale(
            domain=["Primera vuelta", "Segunda vuelta"],
            range=["#64748b", "#d94841"]
        )
    ),
    detail="vuelta_label:N",
    tooltip=[
        alt.Tooltip("region:N", title="Región"),
        alt.Tooltip("anio:Q", title="Año", format="d"),
        alt.Tooltip("vuelta_label:N", title="Vuelta"),
        alt.Tooltip("pct_nulos_blancos:Q", title="% nulos + blancos", format=".2f"),
        alt.Tooltip("nulos_blancos:Q", title="Nulos + blancos", format=","),
        alt.Tooltip("votos_emitidos:Q", title="Votos emitidos", format=",")
    ]
).properties(
    title={
        "text": "El voto nulo y blanco no evoluciona igual en todas las regiones",
        "subtitle": "Porcentaje de votos nulos y blancos por región en elecciones presidenciales chilenas, 1989–2025",
        "anchor": "start",
        "fontSize": 18,
        "subtitleFontSize": 12,
        "subtitleColor": "#374151"
    }
).facet(
    facet="region:N",
    columns=4
).configure_view(
    strokeWidth=0
).configure_axis(
    gridColor="#e5e7eb",
    labelFontSize=9,
    titleFontSize=10
).configure_header(
    labelFontSize=11,
    labelFontWeight="bold"
).configure_legend(
    orient="top",
    title=None
)

grafico_regional

alt.FacetChart(...)

In [ ]:
regiones = sorted(regional_grafico["region"].dropna().unique())

for r in regiones:
    print(r)

Antofagasta
Arica y Parinacota
Atacama
Aysén
Biobío
Coquimbo
La Araucanía
Los Lagos
Los Ríos
Magallanes
Maule
Metropolitana
O’Higgins
Tarapacá
Valparaíso
Ñuble

In [ ]:
region_elegida = "Metropolitana"

datos_region = regional_grafico[
    regional_grafico["region"] == region_elegida
].copy()

display(datos_region)

,eleccion_id,anio,vuelta,region_codigo,region,region_fuente,division_regional,nulos,blancos,nulos_blancos,votos_emitidos,pct_nulos_blancos,nota_limite_regional,vuelta_label
12,1989_1,1989,1,13,Metropolitana,Metropolitana,13 regiones,36799,22729,59528,2853911,2.085839,División regional histórica de 13 regiones: Ta...,Primera vuelta
25,1993_1,1993,1,13,Metropolitana,Metropolitana,13 regiones,102537,43737,146274,2902970,5.038771,División regional histórica de 13 regiones: Ta...,Primera vuelta
38,1999_1,1999,1,13,Metropolitana,METROPOLITANA DE SAN,13 regiones,60139,18794,78933,2849787,2.769786,División regional histórica de 13 regiones: Ta...,Primera vuelta
64,2005_1,2005,1,13,Metropolitana,METROPOLITANA DE SANTIAGO,13 regiones,66417,27541,93958,2776806,3.383672,División regional histórica de 13 regiones: Ta...,Primera vuelta
90,2009_1,2009,1,13,Metropolitana,METROPOLITANA DE SANTIAGO,15 regiones,77328,28855,106183,2785565,3.811902,División regional de 15 regiones: Biobío inclu...,Primera vuelta
120,2013_1,2013,1,13,Metropolitana,METROPOLITANA DE SANTIAGO,15 regiones,24677,15450,40127,2658373,1.509457,División regional de 15 regiones: Biobío inclu...,Primera vuelta
150,2017_1,2017,1,13,Metropolitana,METROPOLITANA DE SANTIAGO,15 regiones,26027,11765,37792,2740686,1.378925,División regional de 15 regiones: Biobío inclu...,Primera vuelta
180,2021_1,2021,1,13,Metropolitana,RM,16 regiones,20029,8860,28889,2906465,0.993957,División regional de 16 regiones.,Primera vuelta
212,2025_1,2025,1,13,Metropolitana,METROPOLITANA DE SANTIAGO,16 regiones,130359,46689,177048,5173843,3.421982,División regional de 16 regiones.,Primera vuelta
51,1999_2,1999,2,13,Metropolitana,METROPOLITANA DE SAN,13 regiones,43098,15803,58901,2856575,2.061945,División regional histórica de 13 regiones: Ta...,Segunda vuelta
77,2005_2,2005,2,13,Metropolitana,METROPOLITANA DE SANTIAGO,13 regiones,64333,17229,81562,2750169,2.965709,División regional histórica de 13 regiones: Ta...,Segunda vuelta
105,2009_2,2009,2,13,Metropolitana,METROPOLITANA DE SANTIAGO,15 regiones,78028,22025,100053,2744498,3.645585,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
135,2013_2,2013,2,13,Metropolitana,METROPOLITANA DE SANTIAGO,15 regiones,38167,14977,53144,2252394,2.359445,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
165,2017_2,2017,2,13,Metropolitana,METROPOLITANA DE SANTIAGO,15 regiones,25226,8281,33507,2850621,1.175428,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
196,2021_2,2021,2,13,Metropolitana,RM,16 regiones,28426,10345,38771,3460078,1.120524,División regional de 16 regiones.,Segunda vuelta
228,2025_2,2025,2,13,Metropolitana,METROPOLITANA DE SANTIAGO,16 regiones,264943,62460,327403,5160085,6.344915,División regional de 16 regiones.,Segunda vuelta

In [ ]:
grafico_region = alt.Chart(datos_region).mark_line(
    point=True,
    strokeWidth=3
).encode(
    x=alt.X(
        "anio:Q",
        title="Año",
        scale=alt.Scale(domain=[1989, 2025]),
        axis=alt.Axis(
            values=[1989, 1993, 1999, 2005, 2009, 2013, 2017, 2021, 2025],
            format="d",
            labelAngle=0
        )
    ),
    y=alt.Y(
        "pct_nulos_blancos:Q",
        title="% nulos + blancos",
        axis=alt.Axis(format=".1f")
    ),
    color=alt.Color(
        "vuelta_label:N",
        title=None,
        scale=alt.Scale(
            domain=["Primera vuelta", "Segunda vuelta"],
            range=["#64748b", "#d94841"]
        )
    ),
    detail="vuelta_label:N",
    tooltip=[
        alt.Tooltip("region:N", title="Región"),
        alt.Tooltip("anio:Q", title="Año", format="d"),
        alt.Tooltip("vuelta_label:N", title="Vuelta"),
        alt.Tooltip("pct_nulos_blancos:Q", title="% nulos + blancos", format=".2f"),
        alt.Tooltip("nulos_blancos:Q", title="Nulos + blancos", format=","),
        alt.Tooltip("votos_emitidos:Q", title="Votos emitidos", format=",")
    ]
).properties(
    title={
        "text": f"Evolución del voto nulo y blanco en {region_elegida}",
        "subtitle": "Porcentaje de votos nulos y blancos en elecciones presidenciales, 1989–2025",
        "anchor": "start",
        "fontSize": 18,
        "subtitleFontSize": 12,
        "subtitleColor": "#374151"
    },
    width=820,
    height=420
).configure_view(
    strokeWidth=0
).configure_axis(
    gridColor="#e5e7eb",
    labelFontSize=11,
    titleFontSize=12
).configure_legend(
    orient="top",
    title=None
)

grafico_region

alt.Chart(...)

In [ ]:
region_elegida = "Valparaíso"

datos_region = regional_grafico[
    regional_grafico["region"] == region_elegida
].copy()

display(datos_region)

grafico_region = alt.Chart(datos_region).mark_line(
    point=True,
    strokeWidth=3
).encode(
    x=alt.X(
        "anio:Q",
        title="Año",
        scale=alt.Scale(domain=[1989, 2025]),
        axis=alt.Axis(
            values=[1989, 1993, 1999, 2005, 2009, 2013, 2017, 2021, 2025],
            format="d",
            labelAngle=0
        )
    ),
    y=alt.Y(
        "pct_nulos_blancos:Q",
        title="% nulos + blancos",
        axis=alt.Axis(format=".1f")
    ),
    color=alt.Color(
        "vuelta_label:N",
        title=None,
        scale=alt.Scale(
            domain=["Primera vuelta", "Segunda vuelta"],
            range=["#64748b", "#d94841"]
        )
    ),
    detail="vuelta_label:N",
    tooltip=[
        alt.Tooltip("region:N", title="Región"),
        alt.Tooltip("anio:Q", title="Año", format="d"),
        alt.Tooltip("vuelta_label:N", title="Vuelta"),
        alt.Tooltip("pct_nulos_blancos:Q", title="% nulos + blancos", format=".2f"),
        alt.Tooltip("nulos_blancos:Q", title="Nulos + blancos", format=","),
        alt.Tooltip("votos_emitidos:Q", title="Votos emitidos", format=",")
    ]
).properties(
    title={
        "text": f"Evolución del voto nulo y blanco en {region_elegida}",
        "subtitle": "Porcentaje de votos nulos y blancos en elecciones presidenciales, 1989–2025",
        "anchor": "start",
        "fontSize": 18,
        "subtitleFontSize": 12,
        "subtitleColor": "#374151"
    },
    width=820,
    height=420
).configure_view(
    strokeWidth=0
).configure_axis(
    gridColor="#e5e7eb",
    labelFontSize=11,
    titleFontSize=12
).configure_legend(
    orient="top",
    title=None
)

grafico_region

,eleccion_id,anio,vuelta,region_codigo,region,region_fuente,division_regional,nulos,blancos,nulos_blancos,votos_emitidos,pct_nulos_blancos,nota_limite_regional,vuelta_label
4,1989_1,1989,1,5,Valparaíso,Valparaíso,13 regiones,10482,7478,17960,774713,2.318278,División regional histórica de 13 regiones: Ta...,Primera vuelta
17,1993_1,1993,1,5,Valparaíso,Valparaíso,13 regiones,31484,14329,45813,814598,5.624001,División regional histórica de 13 regiones: Ta...,Primera vuelta
30,1999_1,1999,1,5,Valparaíso,DE VALPARAISO,13 regiones,21386,6480,27866,807577,3.450569,División regional histórica de 13 regiones: Ta...,Primera vuelta
56,2005_1,2005,1,5,Valparaíso,DE VALPARAISO,13 regiones,22330,8959,31289,802900,3.896998,División regional histórica de 13 regiones: Ta...,Primera vuelta
82,2009_1,2009,1,5,Valparaíso,DE VALPARAISO,15 regiones,24584,9479,34063,817412,4.167176,División regional de 15 regiones: Biobío inclu...,Primera vuelta
112,2013_1,2013,1,5,Valparaíso,DE VALPARAISO,15 regiones,6506,4124,10630,723231,1.469793,División regional de 15 regiones: Biobío inclu...,Primera vuelta
142,2017_1,2017,1,5,Valparaíso,DE VALPARAISO,15 regiones,6234,3267,9501,725747,1.309134,División regional de 15 regiones: Biobío inclu...,Primera vuelta
172,2021_1,2021,1,5,Valparaíso,Valparaiso,16 regiones,6301,2813,9114,802976,1.135028,División regional de 16 regiones.,Primera vuelta
204,2025_1,2025,1,5,Valparaíso,DE VALPARAISO,16 regiones,45035,16481,61516,1451625,4.237734,División regional de 16 regiones.,Primera vuelta
43,1999_2,1999,2,5,Valparaíso,DE VALPARAISO,13 regiones,13825,5426,19251,813325,2.366950,División regional histórica de 13 regiones: Ta...,Segunda vuelta
69,2005_2,2005,2,5,Valparaíso,DE VALPARAISO,13 regiones,19957,5870,25827,799602,3.229982,División regional histórica de 13 regiones: Ta...,Segunda vuelta
97,2009_2,2009,2,5,Valparaíso,DE VALPARAISO,15 regiones,23940,6338,30278,812512,3.726468,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
127,2013_2,2013,2,5,Valparaíso,DE VALPARAISO,15 regiones,9825,3633,13458,614798,2.189012,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
157,2017_2,2017,2,5,Valparaíso,DE VALPARAISO,15 regiones,6255,1829,8084,749632,1.078396,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
188,2021_2,2021,2,5,Valparaíso,Valparaiso,16 regiones,7728,2466,10194,929126,1.097160,División regional de 16 regiones.,Segunda vuelta
220,2025_2,2025,2,5,Valparaíso,DE VALPARAISO,16 regiones,92800,18917,111717,1449153,7.709124,División regional de 16 regiones.,Segunda vuelta

alt.Chart(...)

In [ ]:
region_elegida = "Biobío"

datos_region = regional_grafico[
    regional_grafico["region"] == region_elegida
].copy()

display(datos_region)

grafico_region = alt.Chart(datos_region).mark_line(
    point=True,
    strokeWidth=3
).encode(
    x=alt.X(
        "anio:Q",
        title="Año",
        scale=alt.Scale(domain=[1989, 2025]),
        axis=alt.Axis(
            values=[1989, 1993, 1999, 2005, 2009, 2013, 2017, 2021, 2025],
            format="d",
            labelAngle=0
        )
    ),
    y=alt.Y(
        "pct_nulos_blancos:Q",
        title="% nulos + blancos",
        axis=alt.Axis(format=".1f")
    ),
    color=alt.Color(
        "vuelta_label:N",
        title=None,
        scale=alt.Scale(
            domain=["Primera vuelta", "Segunda vuelta"],
            range=["#64748b", "#d94841"]
        )
    ),
    detail="vuelta_label:N",
    tooltip=[
        alt.Tooltip("region:N", title="Región"),
        alt.Tooltip("anio:Q", title="Año", format="d"),
        alt.Tooltip("vuelta_label:N", title="Vuelta"),
        alt.Tooltip("pct_nulos_blancos:Q", title="% nulos + blancos", format=".2f"),
        alt.Tooltip("nulos_blancos:Q", title="Nulos + blancos", format=","),
        alt.Tooltip("votos_emitidos:Q", title="Votos emitidos", format=",")
    ]
).properties(
    title={
        "text": f"Evolución del voto nulo y blanco en {region_elegida}",
        "subtitle": "Porcentaje de votos nulos y blancos en elecciones presidenciales, 1989–2025",
        "anchor": "start",
        "fontSize": 18,
        "subtitleFontSize": 12,
        "subtitleColor": "#374151"
    },
    width=820,
    height=420
).configure_view(
    strokeWidth=0
).configure_axis(
    gridColor="#e5e7eb",
    labelFontSize=11,
    titleFontSize=12
).configure_legend(
    orient="top",
    title=None
)

grafico_region

,eleccion_id,anio,vuelta,region_codigo,region,region_fuente,division_regional,nulos,blancos,nulos_blancos,votos_emitidos,pct_nulos_blancos,nota_limite_regional,vuelta_label
7,1989_1,1989,1,8,Biobío,Biobío,13 regiones,15572,11578,27150,925058,2.934951,División regional histórica de 13 regiones: Ta...,Primera vuelta
20,1993_1,1993,1,8,Biobío,Biobío,13 regiones,38452,18863,57315,956922,5.989516,División regional histórica de 13 regiones: Ta...,Primera vuelta
33,1999_1,1999,1,8,Biobío,DEL BIO BIO,13 regiones,21305,7841,29146,940463,3.099112,División regional histórica de 13 regiones: Ta...,Primera vuelta
59,2005_1,2005,1,8,Biobío,DEL BIOBIO,13 regiones,24128,11542,35670,935238,3.814002,División regional histórica de 13 regiones: Ta...,Primera vuelta
85,2009_1,2009,1,8,Biobío,DEL BIO BIO,15 regiones,26732,11321,38053,939653,4.049686,División regional de 15 regiones: Biobío inclu...,Primera vuelta
115,2013_1,2013,1,8,Biobío,DEL BIOBIO,15 regiones,10481,6953,17434,853913,2.041660,División regional de 15 regiones: Biobío inclu...,Primera vuelta
145,2017_1,2017,1,8,Biobío,DEL BIOBIO,15 regiones,8628,5668,14296,807835,1.769668,División regional de 15 regiones: Biobío inclu...,Primera vuelta
175,2021_1,2021,1,8,Biobío,Biobio,16 regiones,5289,3199,8488,620395,1.368161,División regional de 16 regiones.,Primera vuelta
207,2025_1,2025,1,8,Biobío,DEL BIOBIO,16 regiones,32279,12125,44404,1219667,3.640666,División regional de 16 regiones.,Primera vuelta
46,1999_2,1999,2,8,Biobío,DEL BIO BIO,13 regiones,12551,5916,18467,952955,1.937867,División regional histórica de 13 regiones: Ta...,Segunda vuelta
72,2005_2,2005,2,8,Biobío,DEL BIOBIO,13 regiones,17966,5664,23630,934484,2.528668,División regional histórica de 13 regiones: Ta...,Segunda vuelta
100,2009_2,2009,2,8,Biobío,DEL BIO BIO,15 regiones,22332,6512,28844,941487,3.063664,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
130,2013_2,2013,2,8,Biobío,DEL BIOBIO,15 regiones,10068,3972,14040,733425,1.914306,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
160,2017_2,2017,2,8,Biobío,DEL BIOBIO,15 regiones,6922,2494,9416,872429,1.079286,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
191,2021_2,2021,2,8,Biobío,Biobio,16 regiones,6420,2122,8542,736687,1.159516,División regional de 16 regiones.,Segunda vuelta
223,2025_2,2025,2,8,Biobío,DEL BIOBIO,16 regiones,77428,15363,92791,1215533,7.633771,División regional de 16 regiones.,Segunda vuelta

alt.Chart(...)

In [ ]:
region_elegida = "La Araucanía"

datos_region = regional_grafico[
    regional_grafico["region"] == region_elegida
].copy()

display(datos_region)

grafico_region = alt.Chart(datos_region).mark_line(
    point=True,
    strokeWidth=3
).encode(
    x=alt.X(
        "anio:Q",
        title="Año",
        scale=alt.Scale(domain=[1989, 2025]),
        axis=alt.Axis(
            values=[1989, 1993, 1999, 2005, 2009, 2013, 2017, 2021, 2025],
            format="d",
            labelAngle=0
        )
    ),
    y=alt.Y(
        "pct_nulos_blancos:Q",
        title="% nulos + blancos",
        axis=alt.Axis(format=".1f")
    ),
    color=alt.Color(
        "vuelta_label:N",
        title=None,
        scale=alt.Scale(
            domain=["Primera vuelta", "Segunda vuelta"],
            range=["#64748b", "#d94841"]
        )
    ),
    detail="vuelta_label:N",
    tooltip=[
        alt.Tooltip("region:N", title="Región"),
        alt.Tooltip("anio:Q", title="Año", format="d"),
        alt.Tooltip("vuelta_label:N", title="Vuelta"),
        alt.Tooltip("pct_nulos_blancos:Q", title="% nulos + blancos", format=".2f"),
        alt.Tooltip("nulos_blancos:Q", title="Nulos + blancos", format=","),
        alt.Tooltip("votos_emitidos:Q", title="Votos emitidos", format=",")
    ]
).properties(
    title={
        "text": f"Evolución del voto nulo y blanco en {region_elegida}",
        "subtitle": "Porcentaje de votos nulos y blancos en elecciones presidenciales, 1989–2025",
        "anchor": "start",
        "fontSize": 18,
        "subtitleFontSize": 12,
        "subtitleColor": "#374151"
    },
    width=820,
    height=420
).configure_view(
    strokeWidth=0
).configure_axis(
    gridColor="#e5e7eb",
    labelFontSize=11,
    titleFontSize=12
).configure_legend(
    orient="top",
    title=None
)

grafico_region

,eleccion_id,anio,vuelta,region_codigo,region,region_fuente,division_regional,nulos,blancos,nulos_blancos,votos_emitidos,pct_nulos_blancos,nota_limite_regional,vuelta_label
8,1989_1,1989,1,9,La Araucanía,La Araucanía,13 regiones,7927,5753,13680,408498,3.348854,División regional histórica de 13 regiones: Ta...,Primera vuelta
21,1993_1,1993,1,9,La Araucanía,La Araucanía,13 regiones,15869,9077,24946,421290,5.921337,División regional histórica de 13 regiones: Ta...,Primera vuelta
34,1999_1,1999,1,9,La Araucanía,DE LA ARAUCANIA,13 regiones,8463,3403,11866,411029,2.886901,División regional histórica de 13 regiones: Ta...,Primera vuelta
60,2005_1,2005,1,9,La Araucanía,DE LA ARAUCANIA,13 regiones,10357,5051,15408,416006,3.703793,División regional histórica de 13 regiones: Ta...,Primera vuelta
86,2009_1,2009,1,9,La Araucanía,DE LA ARAUCANIA,15 regiones,11246,5687,16933,421272,4.019493,División regional de 15 regiones: Biobío inclu...,Primera vuelta
116,2013_1,2013,1,9,La Araucanía,DE LA ARAUCANIA,15 regiones,4855,3626,8481,390034,2.174426,División regional de 15 regiones: Biobío inclu...,Primera vuelta
146,2017_1,2017,1,9,La Araucanía,DE LA ARAUCANIA,15 regiones,4308,3517,7825,373629,2.094324,División regional de 15 regiones: Biobío inclu...,Primera vuelta
176,2021_1,2021,1,9,La Araucanía,Araucania,16 regiones,3774,2536,6310,400139,1.576952,División regional de 16 regiones.,Primera vuelta
208,2025_1,2025,1,9,La Araucanía,DE LA ARAUCANIA,16 regiones,19186,8911,28097,779199,3.605882,División regional de 16 regiones.,Primera vuelta
47,1999_2,1999,2,9,La Araucanía,DE LA ARAUCANIA,13 regiones,4488,2534,7022,420757,1.668897,División regional histórica de 13 regiones: Ta...,Segunda vuelta
73,2005_2,2005,2,9,La Araucanía,DE LA ARAUCANIA,13 regiones,7366,2591,9957,418180,2.381032,División regional histórica de 13 regiones: Ta...,Segunda vuelta
101,2009_2,2009,2,9,La Araucanía,DE LA ARAUCANIA,15 regiones,8348,2505,10853,424151,2.558759,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
131,2013_2,2013,2,9,La Araucanía,DE LA ARAUCANIA,15 regiones,4033,1626,5659,340178,1.663541,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
161,2017_2,2017,2,9,La Araucanía,DE LA ARAUCANIA,15 regiones,2962,1088,4050,407676,0.993436,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
192,2021_2,2021,2,9,La Araucanía,Araucania,16 regiones,3668,1275,4943,467653,1.056980,División regional de 16 regiones.,Segunda vuelta
224,2025_2,2025,2,9,La Araucanía,DE LA ARAUCANIA,16 regiones,40303,8394,48697,776738,6.269424,División regional de 16 regiones.,Segunda vuelta

alt.Chart(...)

In [ ]:
region_elegida = "Maule"

datos_region = regional_grafico[
    regional_grafico["region"] == region_elegida
].copy()

display(datos_region)

grafico_region = alt.Chart(datos_region).mark_line(
    point=True,
    strokeWidth=3
).encode(
    x=alt.X(
        "anio:Q",
        title="Año",
        scale=alt.Scale(domain=[1989, 2025]),
        axis=alt.Axis(
            values=[1989, 1993, 1999, 2005, 2009, 2013, 2017, 2021, 2025],
            format="d",
            labelAngle=0
        )
    ),
    y=alt.Y(
        "pct_nulos_blancos:Q",
        title="% nulos + blancos",
        axis=alt.Axis(format=".1f")
    ),
    color=alt.Color(
        "vuelta_label:N",
        title=None,
        scale=alt.Scale(
            domain=["Primera vuelta", "Segunda vuelta"],
            range=["#64748b", "#d94841"]
        )
    ),
    detail="vuelta_label:N",
    tooltip=[
        alt.Tooltip("region:N", title="Región"),
        alt.Tooltip("anio:Q", title="Año", format="d"),
        alt.Tooltip("vuelta_label:N", title="Vuelta"),
        alt.Tooltip("pct_nulos_blancos:Q", title="% nulos + blancos", format=".2f"),
        alt.Tooltip("nulos_blancos:Q", title="Nulos + blancos", format=","),
        alt.Tooltip("votos_emitidos:Q", title="Votos emitidos", format=",")
    ]
).properties(
    title={
        "text": f"Evolución del voto nulo y blanco en {region_elegida}",
        "subtitle": "Porcentaje de votos nulos y blancos en elecciones presidenciales, 1989–2025",
        "anchor": "start",
        "fontSize": 18,
        "subtitleFontSize": 12,
        "subtitleColor": "#374151"
    },
    width=820,
    height=420
).configure_view(
    strokeWidth=0
).configure_axis(
    gridColor="#e5e7eb",
    labelFontSize=11,
    titleFontSize=12
).configure_legend(
    orient="top",
    title=None
)

grafico_region

,eleccion_id,anio,vuelta,region_codigo,region,region_fuente,division_regional,nulos,blancos,nulos_blancos,votos_emitidos,pct_nulos_blancos,nota_limite_regional,vuelta_label
6,1989_1,1989,1,7,Maule,Maule,13 regiones,7170,5794,12964,454412,2.852918,División regional histórica de 13 regiones: Ta...,Primera vuelta
19,1993_1,1993,1,7,Maule,Maule,13 regiones,16695,10163,26858,470178,5.712305,División regional histórica de 13 regiones: Ta...,Primera vuelta
32,1999_1,1999,1,7,Maule,DEL MAULE,13 regiones,8695,3742,12437,464246,2.678968,División regional histórica de 13 regiones: Ta...,Primera vuelta
58,2005_1,2005,1,7,Maule,DEL MAULE,13 regiones,12402,6202,18604,469216,3.964912,División regional histórica de 13 regiones: Ta...,Primera vuelta
84,2009_1,2009,1,7,Maule,DEL MAULE,15 regiones,12326,6656,18982,473396,4.009751,División regional de 15 regiones: Biobío inclu...,Primera vuelta
114,2013_1,2013,1,7,Maule,DEL MAULE,15 regiones,4699,3534,8233,438073,1.879367,División regional de 15 regiones: Biobío inclu...,Primera vuelta
144,2017_1,2017,1,7,Maule,DEL MAULE,15 regiones,4303,3354,7657,409775,1.868586,División regional de 15 regiones: Biobío inclu...,Primera vuelta
174,2021_1,2021,1,7,Maule,Maule,16 regiones,3711,2424,6135,409512,1.498125,División regional de 16 regiones.,Primera vuelta
206,2025_1,2025,1,7,Maule,DEL MAULE,16 regiones,23029,9968,32997,862103,3.827501,División regional de 16 regiones.,Primera vuelta
45,1999_2,1999,2,7,Maule,DEL MAULE,13 regiones,4947,2815,7762,470649,1.649212,División regional histórica de 13 regiones: Ta...,Segunda vuelta
71,2005_2,2005,2,7,Maule,DEL MAULE,13 regiones,8275,3063,11338,469921,2.412746,División regional histórica de 13 regiones: Ta...,Segunda vuelta
99,2009_2,2009,2,7,Maule,DEL MAULE,15 regiones,8928,2825,11753,474834,2.475181,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
129,2013_2,2013,2,7,Maule,DEL MAULE,15 regiones,3855,1565,5420,386240,1.403273,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
159,2017_2,2017,2,7,Maule,DEL MAULE,15 regiones,2680,926,3606,445438,0.809540,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
190,2021_2,2021,2,7,Maule,Maule,16 regiones,3542,1276,4818,495354,0.972638,División regional de 16 regiones.,Segunda vuelta
222,2025_2,2025,2,7,Maule,DEL MAULE,16 regiones,48586,8662,57248,860933,6.649530,División regional de 16 regiones.,Segunda vuelta

alt.Chart(...)

In [ ]:
region_elegida = "O'Higgins"

datos_region = regional_grafico[
    regional_grafico["region"] == region_elegida
].copy()

display(datos_region)

grafico_region = alt.Chart(datos_region).mark_line(
    point=True,
    strokeWidth=3
).encode(
    x=alt.X(
        "anio:Q",
        title="Año",
        scale=alt.Scale(domain=[1989, 2025]),
        axis=alt.Axis(
            values=[1989, 1993, 1999, 2005, 2009, 2013, 2017, 2021, 2025],
            format="d",
            labelAngle=0
        )
    ),
    y=alt.Y(
        "pct_nulos_blancos:Q",
        title="% nulos + blancos",
        axis=alt.Axis(format=".1f")
    ),
    color=alt.Color(
        "vuelta_label:N",
        title=None,
        scale=alt.Scale(
            domain=["Primera vuelta", "Segunda vuelta"],
            range=["#64748b", "#d94841"]
        )
    ),
    detail="vuelta_label:N",
    tooltip=[
        alt.Tooltip("region:N", title="Región"),
        alt.Tooltip("anio:Q", title="Año", format="d"),
        alt.Tooltip("vuelta_label:N", title="Vuelta"),
        alt.Tooltip("pct_nulos_blancos:Q", title="% nulos + blancos", format=".2f"),
        alt.Tooltip("nulos_blancos:Q", title="Nulos + blancos", format=","),
        alt.Tooltip("votos_emitidos:Q", title="Votos emitidos", format=",")
    ]
).properties(
    title={
        "text": f"Evolución del voto nulo y blanco en {region_elegida}",
        "subtitle": "Porcentaje de votos nulos y blancos en elecciones presidenciales, 1989–2025",
        "anchor": "start",
        "fontSize": 18,
        "subtitleFontSize": 12,
        "subtitleColor": "#374151"
    },
    width=820,
    height=420
).configure_view(
    strokeWidth=0
).configure_axis(
    gridColor="#e5e7eb",
    labelFontSize=11,
    titleFontSize=12
).configure_legend(
    orient="top",
    title=None
)

grafico_region

Empty DataFrame
Columns: [eleccion_id, anio, vuelta, region_codigo, region, region_fuente, division_regional, nulos, blancos, nulos_blancos, votos_emitidos, pct_nulos_blancos, nota_limite_regional, vuelta_label]
Index: []

alt.Chart(...)

In [ ]:
region_elegida = "Coquimbo"

datos_region = regional_grafico[
    regional_grafico["region"] == region_elegida
].copy()

display(datos_region)

grafico_region = alt.Chart(datos_region).mark_line(
    point=True,
    strokeWidth=3
).encode(
    x=alt.X(
        "anio:Q",
        title="Año",
        scale=alt.Scale(domain=[1989, 2025]),
        axis=alt.Axis(
            values=[1989, 1993, 1999, 2005, 2009, 2013, 2017, 2021, 2025],
            format="d",
            labelAngle=0
        )
    ),
    y=alt.Y(
        "pct_nulos_blancos:Q",
        title="% nulos + blancos",
        axis=alt.Axis(format=".1f")
    ),
    color=alt.Color(
        "vuelta_label:N",
        title=None,
        scale=alt.Scale(
            domain=["Primera vuelta", "Segunda vuelta"],
            range=["#64748b", "#d94841"]
        )
    ),
    detail="vuelta_label:N",
    tooltip=[
        alt.Tooltip("region:N", title="Región"),
        alt.Tooltip("anio:Q", title="Año", format="d"),
        alt.Tooltip("vuelta_label:N", title="Vuelta"),
        alt.Tooltip("pct_nulos_blancos:Q", title="% nulos + blancos", format=".2f"),
        alt.Tooltip("nulos_blancos:Q", title="Nulos + blancos", format=","),
        alt.Tooltip("votos_emitidos:Q", title="Votos emitidos", format=",")
    ]
).properties(
    title={
        "text": f"Evolución del voto nulo y blanco en {region_elegida}",
        "subtitle": "Porcentaje de votos nulos y blancos en elecciones presidenciales, 1989–2025",
        "anchor": "start",
        "fontSize": 18,
        "subtitleFontSize": 12,
        "subtitleColor": "#374151"
    },
    width=820,
    height=420
).configure_view(
    strokeWidth=0
).configure_axis(
    gridColor="#e5e7eb",
    labelFontSize=11,
    titleFontSize=12
).configure_legend(
    orient="top",
    title=None
)

grafico_region

,eleccion_id,anio,vuelta,region_codigo,region,region_fuente,division_regional,nulos,blancos,nulos_blancos,votos_emitidos,pct_nulos_blancos,nota_limite_regional,vuelta_label
3,1989_1,1989,1,4,Coquimbo,Coquimbo,13 regiones,3915,3881,7796,254929,3.058106,División regional histórica de 13 regiones: Ta...,Primera vuelta
16,1993_1,1993,1,4,Coquimbo,Coquimbo,13 regiones,10124,7329,17453,268842,6.491917,División regional histórica de 13 regiones: Ta...,Primera vuelta
29,1999_1,1999,1,4,Coquimbo,DE COQUIMBO,13 regiones,6255,3091,9346,271691,3.439937,División regional histórica de 13 regiones: Ta...,Primera vuelta
55,2005_1,2005,1,4,Coquimbo,DE COQUIMBO,13 regiones,6816,4549,11365,275153,4.130429,División regional histórica de 13 regiones: Ta...,Primera vuelta
81,2009_1,2009,1,4,Coquimbo,DE COQUIMBO,15 regiones,6817,4094,10911,277634,3.929994,División regional de 15 regiones: Biobío inclu...,Primera vuelta
111,2013_1,2013,1,4,Coquimbo,DE COQUIMBO,15 regiones,2499,2193,4692,259764,1.806255,División regional de 15 regiones: Biobío inclu...,Primera vuelta
141,2017_1,2017,1,4,Coquimbo,DE COQUIMBO,15 regiones,2315,1780,4095,257283,1.591633,División regional de 15 regiones: Biobío inclu...,Primera vuelta
171,2021_1,2021,1,4,Coquimbo,Coquimbo,16 regiones,2141,1321,3462,267015,1.296556,División regional de 16 regiones.,Primera vuelta
203,2025_1,2025,1,4,Coquimbo,DE COQUIMBO,16 regiones,18175,8093,26268,585884,4.483481,División regional de 16 regiones.,Primera vuelta
42,1999_2,1999,2,4,Coquimbo,DE COQUIMBO,13 regiones,3795,2238,6033,274687,2.196318,División regional histórica de 13 regiones: Ta...,Segunda vuelta
68,2005_2,2005,2,4,Coquimbo,DE COQUIMBO,13 regiones,5779,2530,8309,275454,3.016475,División regional histórica de 13 regiones: Ta...,Segunda vuelta
96,2009_2,2009,2,4,Coquimbo,DE COQUIMBO,15 regiones,6998,2599,9597,278442,3.446678,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
126,2013_2,2013,2,4,Coquimbo,DE COQUIMBO,15 regiones,2541,1156,3697,223985,1.650557,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
156,2017_2,2017,2,4,Coquimbo,DE COQUIMBO,15 regiones,1839,708,2547,266673,0.955102,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
187,2021_2,2021,2,4,Coquimbo,Coquimbo,16 regiones,2664,966,3630,318499,1.139721,División regional de 16 regiones.,Segunda vuelta
219,2025_2,2025,2,4,Coquimbo,DE COQUIMBO,16 regiones,42661,8795,51456,583378,8.820353,División regional de 16 regiones.,Segunda vuelta

alt.Chart(...)

In [ ]:
region_elegida = "Antofagasta"

datos_region = regional_grafico[
    regional_grafico["region"] == region_elegida
].copy()

display(datos_region)

grafico_region = alt.Chart(datos_region).mark_line(
    point=True,
    strokeWidth=3
).encode(
    x=alt.X(
        "anio:Q",
        title="Año",
        scale=alt.Scale(domain=[1989, 2025]),
        axis=alt.Axis(
            values=[1989, 1993, 1999, 2005, 2009, 2013, 2017, 2021, 2025],
            format="d",
            labelAngle=0
        )
    ),
    y=alt.Y(
        "pct_nulos_blancos:Q",
        title="% nulos + blancos",
        axis=alt.Axis(format=".1f")
    ),
    color=alt.Color(
        "vuelta_label:N",
        title=None,
        scale=alt.Scale(
            domain=["Primera vuelta", "Segunda vuelta"],
            range=["#64748b", "#d94841"]
        )
    ),
    detail="vuelta_label:N",
    tooltip=[
        alt.Tooltip("region:N", title="Región"),
        alt.Tooltip("anio:Q", title="Año", format="d"),
        alt.Tooltip("vuelta_label:N", title="Vuelta"),
        alt.Tooltip("pct_nulos_blancos:Q", title="% nulos + blancos", format=".2f"),
        alt.Tooltip("nulos_blancos:Q", title="Nulos + blancos", format=","),
        alt.Tooltip("votos_emitidos:Q", title="Votos emitidos", format=",")
    ]
).properties(
    title={
        "text": f"Evolución del voto nulo y blanco en {region_elegida}",
        "subtitle": "Porcentaje de votos nulos y blancos en elecciones presidenciales, 1989–2025",
        "anchor": "start",
        "fontSize": 18,
        "subtitleFontSize": 12,
        "subtitleColor": "#374151"
    },
    width=820,
    height=420
).configure_view(
    strokeWidth=0
).configure_axis(
    gridColor="#e5e7eb",
    labelFontSize=11,
    titleFontSize=12
).configure_legend(
    orient="top",
    title=None
)

grafico_region

,eleccion_id,anio,vuelta,region_codigo,region,region_fuente,division_regional,nulos,blancos,nulos_blancos,votos_emitidos,pct_nulos_blancos,nota_limite_regional,vuelta_label
1,1989_1,1989,1,2,Antofagasta,Antofagasta,13 regiones,3191,1980,5171,214583,2.409790,División regional histórica de 13 regiones: Ta...,Primera vuelta
14,1993_1,1993,1,2,Antofagasta,Antofagasta,13 regiones,10375,3814,14189,216911,6.541393,División regional histórica de 13 regiones: Ta...,Primera vuelta
27,1999_1,1999,1,2,Antofagasta,DE ANTOFAGASTA,13 regiones,5835,1705,7540,206083,3.658720,División regional histórica de 13 regiones: Ta...,Primera vuelta
53,2005_1,2005,1,2,Antofagasta,DE ANTOFAGASTA,13 regiones,5705,2007,7712,202407,3.810145,División regional histórica de 13 regiones: Ta...,Primera vuelta
79,2009_1,2009,1,2,Antofagasta,DE ANTOFAGASTA,15 regiones,7259,2063,9322,198837,4.688262,División regional de 15 regiones: Biobío inclu...,Primera vuelta
109,2013_1,2013,1,2,Antofagasta,DE ANTOFAGASTA,15 regiones,1607,718,2325,176671,1.316005,División regional de 15 regiones: Biobío inclu...,Primera vuelta
139,2017_1,2017,1,2,Antofagasta,DE ANTOFAGASTA,15 regiones,1626,596,2222,180282,1.232514,División regional de 15 regiones: Biobío inclu...,Primera vuelta
169,2021_1,2021,1,2,Antofagasta,Antofagasta,16 regiones,1684,678,2362,203838,1.158763,División regional de 16 regiones.,Primera vuelta
201,2025_1,2025,1,2,Antofagasta,DE ANTOFAGASTA,16 regiones,12578,4576,17154,411661,4.167021,División regional de 16 regiones.,Primera vuelta
40,1999_2,1999,2,2,Antofagasta,DE ANTOFAGASTA,13 regiones,3805,1278,5083,204922,2.480456,División regional histórica de 13 regiones: Ta...,Segunda vuelta
66,2005_2,2005,2,2,Antofagasta,DE ANTOFAGASTA,13 regiones,5147,1259,6406,195784,3.271973,División regional histórica de 13 regiones: Ta...,Segunda vuelta
94,2009_2,2009,2,2,Antofagasta,DE ANTOFAGASTA,15 regiones,7548,1536,9084,190514,4.768154,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
124,2013_2,2013,2,2,Antofagasta,DE ANTOFAGASTA,15 regiones,2358,656,3014,131326,2.295052,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
154,2017_2,2017,2,2,Antofagasta,DE ANTOFAGASTA,15 regiones,1634,353,1987,182380,1.089483,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
185,2021_2,2021,2,2,Antofagasta,Antofagasta,16 regiones,2515,633,3148,217254,1.448995,División regional de 16 regiones.,Segunda vuelta
217,2025_2,2025,2,2,Antofagasta,DE ANTOFAGASTA,16 regiones,36870,5853,42723,407592,10.481805,División regional de 16 regiones.,Segunda vuelta

alt.Chart(...)

In [ ]:
region_elegida = "Tarapacá"

datos_region = regional_grafico[
    regional_grafico["region"] == region_elegida
].copy()

display(datos_region)

grafico_region = alt.Chart(datos_region).mark_line(
    point=True,
    strokeWidth=3
).encode(
    x=alt.X(
        "anio:Q",
        title="Año",
        scale=alt.Scale(domain=[1989, 2025]),
        axis=alt.Axis(
            values=[1989, 1993, 1999, 2005, 2009, 2013, 2017, 2021, 2025],
            format="d",
            labelAngle=0
        )
    ),
    y=alt.Y(
        "pct_nulos_blancos:Q",
        title="% nulos + blancos",
        axis=alt.Axis(format=".1f")
    ),
    color=alt.Color(
        "vuelta_label:N",
        title=None,
        scale=alt.Scale(
            domain=["Primera vuelta", "Segunda vuelta"],
            range=["#64748b", "#d94841"]
        )
    ),
    detail="vuelta_label:N",
    tooltip=[
        alt.Tooltip("region:N", title="Región"),
        alt.Tooltip("anio:Q", title="Año", format="d"),
        alt.Tooltip("vuelta_label:N", title="Vuelta"),
        alt.Tooltip("pct_nulos_blancos:Q", title="% nulos + blancos", format=".2f"),
        alt.Tooltip("nulos_blancos:Q", title="Nulos + blancos", format=","),
        alt.Tooltip("votos_emitidos:Q", title="Votos emitidos", format=",")
    ]
).properties(
    title={
        "text": f"Evolución del voto nulo y blanco en {region_elegida}",
        "subtitle": "Porcentaje de votos nulos y blancos en elecciones presidenciales, 1989–2025",
        "anchor": "start",
        "fontSize": 18,
        "subtitleFontSize": 12,
        "subtitleColor": "#374151"
    },
    width=820,
    height=420
).configure_view(
    strokeWidth=0
).configure_axis(
    gridColor="#e5e7eb",
    labelFontSize=11,
    titleFontSize=12
).configure_legend(
    orient="top",
    title=None
)

grafico_region

,eleccion_id,anio,vuelta,region_codigo,region,region_fuente,division_regional,nulos,blancos,nulos_blancos,votos_emitidos,pct_nulos_blancos,nota_limite_regional,vuelta_label
0,1989_1,1989,1,1,Tarapacá,Tarapacá,13 regiones,2833,1739,4572,170476,2.681902,División regional histórica de 13 regiones: Ta...,Primera vuelta
13,1993_1,1993,1,1,Tarapacá,Tarapacá,13 regiones,6884,3226,10110,176663,5.722760,División regional histórica de 13 regiones: Ta...,Primera vuelta
26,1999_1,1999,1,1,Tarapacá,DE TARAPACA,13 regiones,4972,1475,6447,178016,3.621585,División regional histórica de 13 regiones: Ta...,Primera vuelta
52,2005_1,2005,1,1,Tarapacá,DE TARAPACA,13 regiones,5241,1902,7143,180545,3.956354,División regional histórica de 13 regiones: Ta...,Primera vuelta
78,2009_1,2009,1,1,Tarapacá,DE TARAPACA,15 regiones,2600,1016,3616,100653,3.592541,División regional de 15 regiones: Biobío inclu...,Primera vuelta
108,2013_1,2013,1,1,Tarapacá,DE TARAPACA,15 regiones,595,345,940,86117,1.091538,División regional de 15 regiones: Biobío inclu...,Primera vuelta
138,2017_1,2017,1,1,Tarapacá,DE TARAPACA,15 regiones,675,344,1019,96246,1.058745,División regional de 15 regiones: Biobío inclu...,Primera vuelta
168,2021_1,2021,1,1,Tarapacá,Tarapaca,16 regiones,826,362,1188,110354,1.076536,División regional de 16 regiones.,Primera vuelta
200,2025_1,2025,1,1,Tarapacá,DE TARAPACA,16 regiones,5165,2149,7314,213405,3.427286,División regional de 16 regiones.,Primera vuelta
39,1999_2,1999,2,1,Tarapacá,DE TARAPACA,13 regiones,3523,1173,4696,178254,2.634443,División regional histórica de 13 regiones: Ta...,Segunda vuelta
65,2005_2,2005,2,1,Tarapacá,DE TARAPACA,13 regiones,4682,1315,5997,177018,3.387791,División regional histórica de 13 regiones: Ta...,Segunda vuelta
93,2009_2,2009,2,1,Tarapacá,DE TARAPACA,15 regiones,3251,935,4186,97719,4.283711,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
123,2013_2,2013,2,1,Tarapacá,DE TARAPACA,15 regiones,972,358,1330,65299,2.036785,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
153,2017_2,2017,2,1,Tarapacá,DE TARAPACA,15 regiones,675,164,839,93324,0.899018,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
184,2021_2,2021,2,1,Tarapacá,Tarapaca,16 regiones,1107,330,1437,115399,1.245245,División regional de 16 regiones.,Segunda vuelta
216,2025_2,2025,2,1,Tarapacá,DE TARAPACA,16 regiones,14813,2529,17342,212121,8.175522,División regional de 16 regiones.,Segunda vuelta

alt.Chart(...)

In [ ]:
region_elegida = "Atacama"

datos_region = regional_grafico[
    regional_grafico["region"] == region_elegida
].copy()

display(datos_region)

grafico_region = alt.Chart(datos_region).mark_line(
    point=True,
    strokeWidth=3
).encode(
    x=alt.X(
        "anio:Q",
        title="Año",
        scale=alt.Scale(domain=[1989, 2025]),
        axis=alt.Axis(
            values=[1989, 1993, 1999, 2005, 2009, 2013, 2017, 2021, 2025],
            format="d",
            labelAngle=0
        )
    ),
    y=alt.Y(
        "pct_nulos_blancos:Q",
        title="% nulos + blancos",
        axis=alt.Axis(format=".1f")
    ),
    color=alt.Color(
        "vuelta_label:N",
        title=None,
        scale=alt.Scale(
            domain=["Primera vuelta", "Segunda vuelta"],
            range=["#64748b", "#d94841"]
        )
    ),
    detail="vuelta_label:N",
    tooltip=[
        alt.Tooltip("region:N", title="Región"),
        alt.Tooltip("anio:Q", title="Año", format="d"),
        alt.Tooltip("vuelta_label:N", title="Vuelta"),
        alt.Tooltip("pct_nulos_blancos:Q", title="% nulos + blancos", format=".2f"),
        alt.Tooltip("nulos_blancos:Q", title="Nulos + blancos", format=","),
        alt.Tooltip("votos_emitidos:Q", title="Votos emitidos", format=",")
    ]
).properties(
    title={
        "text": f"Evolución del voto nulo y blanco en {region_elegida}",
        "subtitle": "Porcentaje de votos nulos y blancos en elecciones presidenciales, 1989–2025",
        "anchor": "start",
        "fontSize": 18,
        "subtitleFontSize": 12,
        "subtitleColor": "#374151"
    },
    width=820,
    height=420
).configure_view(
    strokeWidth=0
).configure_axis(
    gridColor="#e5e7eb",
    labelFontSize=11,
    titleFontSize=12
).configure_legend(
    orient="top",
    title=None
)

grafico_region

,eleccion_id,anio,vuelta,region_codigo,region,region_fuente,division_regional,nulos,blancos,nulos_blancos,votos_emitidos,pct_nulos_blancos,nota_limite_regional,vuelta_label
2,1989_1,1989,1,3,Atacama,Atacama,13 regiones,1385,1501,2886,114639,2.517468,División regional histórica de 13 regiones: Ta...,Primera vuelta
15,1993_1,1993,1,3,Atacama,Atacama,13 regiones,4096,2734,6830,120020,5.690718,División regional histórica de 13 regiones: Ta...,Primera vuelta
28,1999_1,1999,1,3,Atacama,DE ATACAMA,13 regiones,2447,1032,3479,114489,3.038720,División regional histórica de 13 regiones: Ta...,Primera vuelta
54,2005_1,2005,1,3,Atacama,DE ATACAMA,13 regiones,2590,1552,4142,114146,3.628686,División regional histórica de 13 regiones: Ta...,Primera vuelta
80,2009_1,2009,1,3,Atacama,DE ATACAMA,15 regiones,3221,1629,4850,114601,4.232075,División regional de 15 regiones: Biobío inclu...,Primera vuelta
110,2013_1,2013,1,3,Atacama,DE ATACAMA,15 regiones,873,675,1548,99162,1.561082,División regional de 15 regiones: Biobío inclu...,Primera vuelta
140,2017_1,2017,1,3,Atacama,DE ATACAMA,15 regiones,735,572,1307,100872,1.295701,División regional de 15 regiones: Biobío inclu...,Primera vuelta
170,2021_1,2021,1,3,Atacama,Atacama,16 regiones,738,367,1105,107185,1.030928,División regional de 16 regiones.,Primera vuelta
202,2025_1,2025,1,3,Atacama,DE ATACAMA,16 regiones,5886,2755,8641,210865,4.097883,División regional de 16 regiones.,Primera vuelta
41,1999_2,1999,2,3,Atacama,DE ATACAMA,13 regiones,1681,782,2463,115706,2.128671,División regional histórica de 13 regiones: Ta...,Segunda vuelta
67,2005_2,2005,2,3,Atacama,DE ATACAMA,13 regiones,2481,1001,3482,113415,3.070141,División regional histórica de 13 regiones: Ta...,Segunda vuelta
95,2009_2,2009,2,3,Atacama,DE ATACAMA,15 regiones,3261,978,4239,113204,3.744567,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
125,2013_2,2013,2,3,Atacama,DE ATACAMA,15 regiones,973,441,1414,80579,1.754800,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
155,2017_2,2017,2,3,Atacama,DE ATACAMA,15 regiones,616,206,822,102750,0.800000,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
186,2021_2,2021,2,3,Atacama,Atacama,16 regiones,993,294,1287,117716,1.093309,División regional de 16 regiones.,Segunda vuelta
218,2025_2,2025,2,3,Atacama,DE ATACAMA,16 regiones,16879,3080,19959,209978,9.505282,División regional de 16 regiones.,Segunda vuelta

alt.Chart(...)

In [ ]:
region_elegida = "Los Lagos"

datos_region = regional_grafico[
    regional_grafico["region"] == region_elegida
].copy()

display(datos_region)

grafico_region = alt.Chart(datos_region).mark_line(
    point=True,
    strokeWidth=3
).encode(
    x=alt.X(
        "anio:Q",
        title="Año",
        scale=alt.Scale(domain=[1989, 2025]),
        axis=alt.Axis(
            values=[1989, 1993, 1999, 2005, 2009, 2013, 2017, 2021, 2025],
            format="d",
            labelAngle=0
        )
    ),
    y=alt.Y(
        "pct_nulos_blancos:Q",
        title="% nulos + blancos",
        axis=alt.Axis(format=".1f")
    ),
    color=alt.Color(
        "vuelta_label:N",
        title=None,
        scale=alt.Scale(
            domain=["Primera vuelta", "Segunda vuelta"],
            range=["#64748b", "#d94841"]
        )
    ),
    detail="vuelta_label:N",
    tooltip=[
        alt.Tooltip("region:N", title="Región"),
        alt.Tooltip("anio:Q", title="Año", format="d"),
        alt.Tooltip("vuelta_label:N", title="Vuelta"),
        alt.Tooltip("pct_nulos_blancos:Q", title="% nulos + blancos", format=".2f"),
        alt.Tooltip("nulos_blancos:Q", title="Nulos + blancos", format=","),
        alt.Tooltip("votos_emitidos:Q", title="Votos emitidos", format=",")
    ]
).properties(
    title={
        "text": f"Evolución del voto nulo y blanco en {region_elegida}",
        "subtitle": "Porcentaje de votos nulos y blancos en elecciones presidenciales, 1989–2025",
        "anchor": "start",
        "fontSize": 18,
        "subtitleFontSize": 12,
        "subtitleColor": "#374151"
    },
    width=820,
    height=420
).configure_view(
    strokeWidth=0
).configure_axis(
    gridColor="#e5e7eb",
    labelFontSize=11,
    titleFontSize=12
).configure_legend(
    orient="top",
    title=None
)

grafico_region

,eleccion_id,anio,vuelta,region_codigo,region,region_fuente,division_regional,nulos,blancos,nulos_blancos,votos_emitidos,pct_nulos_blancos,nota_limite_regional,vuelta_label
9,1989_1,1989,1,10,Los Lagos,Los Lagos,13 regiones,7801,6649,14450,488347,2.958962,División regional histórica de 13 regiones: Ta...,Primera vuelta
22,1993_1,1993,1,10,Los Lagos,Los Lagos,13 regiones,16670,12706,29376,508816,5.773403,División regional histórica de 13 regiones: Ta...,Primera vuelta
35,1999_1,1999,1,10,Los Lagos,DE LOS LAGOS,13 regiones,9083,4926,14009,505501,2.771310,División regional histórica de 13 regiones: Ta...,Primera vuelta
61,2005_1,2005,1,10,Los Lagos,DE LOS LAGOS,13 regiones,11661,8126,19787,512936,3.857596,División regional histórica de 13 regiones: Ta...,Primera vuelta
87,2009_1,2009,1,10,Los Lagos,DE LOS LAGOS,15 regiones,7909,5444,13353,347524,3.842325,División regional de 15 regiones: Biobío inclu...,Primera vuelta
117,2013_1,2013,1,10,Los Lagos,DE LOS LAGOS,15 regiones,3361,3563,6924,313901,2.205791,División regional de 15 regiones: Biobío inclu...,Primera vuelta
147,2017_1,2017,1,10,Los Lagos,DE LOS LAGOS,15 regiones,3071,3029,6100,304214,2.005167,División regional de 15 regiones: Biobío inclu...,Primera vuelta
177,2021_1,2021,1,10,Los Lagos,Los Lagos,16 regiones,2733,2471,5204,330951,1.572438,División regional de 16 regiones.,Primera vuelta
209,2025_1,2025,1,10,Los Lagos,DE LOS LAGOS,16 regiones,18616,9278,27894,673366,4.142472,División regional de 16 regiones.,Primera vuelta
48,1999_2,1999,2,10,Los Lagos,DE LOS LAGOS,13 regiones,4907,3511,8418,514550,1.635993,División regional histórica de 13 regiones: Ta...,Segunda vuelta
74,2005_2,2005,2,10,Los Lagos,DE LOS LAGOS,13 regiones,8434,3851,12285,512786,2.395736,División regional histórica de 13 regiones: Ta...,Segunda vuelta
102,2009_2,2009,2,10,Los Lagos,DE LOS LAGOS,15 regiones,7343,2723,10066,347338,2.898042,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
132,2013_2,2013,2,10,Los Lagos,DE LOS LAGOS,15 regiones,2964,1381,4345,271558,1.600027,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
162,2017_2,2017,2,10,Los Lagos,DE LOS LAGOS,15 regiones,2293,993,3286,324871,1.011478,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
193,2021_2,2021,2,10,Los Lagos,Los Lagos,16 regiones,3066,1233,4299,387821,1.108501,División regional de 16 regiones.,Segunda vuelta
225,2025_2,2025,2,10,Los Lagos,DE LOS LAGOS,16 regiones,40351,8993,49344,672084,7.341939,División regional de 16 regiones.,Segunda vuelta

alt.Chart(...)

In [ ]:
region_elegida = "Los Ríos"

datos_region = regional_grafico[
    regional_grafico["region"] == region_elegida
].copy()

display(datos_region)

grafico_region = alt.Chart(datos_region).mark_line(
    point=True,
    strokeWidth=3
).encode(
    x=alt.X(
        "anio:Q",
        title="Año",
        scale=alt.Scale(domain=[1989, 2025]),
        axis=alt.Axis(
            values=[1989, 1993, 1999, 2005, 2009, 2013, 2017, 2021, 2025],
            format="d",
            labelAngle=0
        )
    ),
    y=alt.Y(
        "pct_nulos_blancos:Q",
        title="% nulos + blancos",
        axis=alt.Axis(format=".1f")
    ),
    color=alt.Color(
        "vuelta_label:N",
        title=None,
        scale=alt.Scale(
            domain=["Primera vuelta", "Segunda vuelta"],
            range=["#64748b", "#d94841"]
        )
    ),
    detail="vuelta_label:N",
    tooltip=[
        alt.Tooltip("region:N", title="Región"),
        alt.Tooltip("anio:Q", title="Año", format="d"),
        alt.Tooltip("vuelta_label:N", title="Vuelta"),
        alt.Tooltip("pct_nulos_blancos:Q", title="% nulos + blancos", format=".2f"),
        alt.Tooltip("nulos_blancos:Q", title="Nulos + blancos", format=","),
        alt.Tooltip("votos_emitidos:Q", title="Votos emitidos", format=",")
    ]
).properties(
    title={
        "text": f"Evolución del voto nulo y blanco en {region_elegida}",
        "subtitle": "Porcentaje de votos nulos y blancos en elecciones presidenciales, 1989–2025",
        "anchor": "start",
        "fontSize": 18,
        "subtitleFontSize": 12,
        "subtitleColor": "#374151"
    },
    width=820,
    height=420
).configure_view(
    strokeWidth=0
).configure_axis(
    gridColor="#e5e7eb",
    labelFontSize=11,
    titleFontSize=12
).configure_legend(
    orient="top",
    title=None
)

grafico_region

,eleccion_id,anio,vuelta,region_codigo,region,region_fuente,division_regional,nulos,blancos,nulos_blancos,votos_emitidos,pct_nulos_blancos,nota_limite_regional,vuelta_label
91,2009_1,2009,1,14,Los Ríos,DE LOS RIOS,15 regiones,3716,2011,5727,174500,3.281948,División regional de 15 regiones: Biobío inclu...,Primera vuelta
121,2013_1,2013,1,14,Los Ríos,DE LOS RIOS,15 regiones,1766,1334,3100,161729,1.916787,División regional de 15 regiones: Biobío inclu...,Primera vuelta
151,2017_1,2017,1,14,Los Ríos,DE LOS RIOS,15 regiones,1573,1205,2778,155536,1.786082,División regional de 15 regiones: Biobío inclu...,Primera vuelta
181,2021_1,2021,1,14,Los Ríos,Los Rios,16 regiones,1426,1076,2502,162125,1.543254,División regional de 16 regiones.,Primera vuelta
213,2025_1,2025,1,14,Los Ríos,DE LOS RIOS,16 regiones,7903,3350,11253,313874,3.585197,División regional de 16 regiones.,Primera vuelta
106,2009_2,2009,2,14,Los Ríos,DE LOS RIOS,15 regiones,3696,1249,4945,174998,2.825747,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
136,2013_2,2013,2,14,Los Ríos,DE LOS RIOS,15 regiones,1638,649,2287,138160,1.655327,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
166,2017_2,2017,2,14,Los Ríos,DE LOS RIOS,15 regiones,1255,471,1726,164306,1.050479,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
197,2021_2,2021,2,14,Los Ríos,Los Rios,16 regiones,1419,604,2023,190827,1.060123,División regional de 16 regiones.,Segunda vuelta
229,2025_2,2025,2,14,Los Ríos,DE LOS RIOS,16 regiones,16628,3673,20301,312880,6.488430,División regional de 16 regiones.,Segunda vuelta

alt.Chart(...)

In [ ]:
region_elegida = "Arica y Parinacota"

datos_region = regional_grafico[
    regional_grafico["region"] == region_elegida
].copy()

display(datos_region)

grafico_region = alt.Chart(datos_region).mark_line(
    point=True,
    strokeWidth=3
).encode(
    x=alt.X(
        "anio:Q",
        title="Año",
        scale=alt.Scale(domain=[1989, 2025]),
        axis=alt.Axis(
            values=[1989, 1993, 1999, 2005, 2009, 2013, 2017, 2021, 2025],
            format="d",
            labelAngle=0
        )
    ),
    y=alt.Y(
        "pct_nulos_blancos:Q",
        title="% nulos + blancos",
        axis=alt.Axis(format=".1f")
    ),
    color=alt.Color(
        "vuelta_label:N",
        title=None,
        scale=alt.Scale(
            domain=["Primera vuelta", "Segunda vuelta"],
            range=["#64748b", "#d94841"]
        )
    ),
    detail="vuelta_label:N",
    tooltip=[
        alt.Tooltip("region:N", title="Región"),
        alt.Tooltip("anio:Q", title="Año", format="d"),
        alt.Tooltip("vuelta_label:N", title="Vuelta"),
        alt.Tooltip("pct_nulos_blancos:Q", title="% nulos + blancos", format=".2f"),
        alt.Tooltip("nulos_blancos:Q", title="Nulos + blancos", format=","),
        alt.Tooltip("votos_emitidos:Q", title="Votos emitidos", format=",")
    ]
).properties(
    title={
        "text": f"Evolución del voto nulo y blanco en {region_elegida}",
        "subtitle": "Porcentaje de votos nulos y blancos en elecciones presidenciales, 1989–2025",
        "anchor": "start",
        "fontSize": 18,
        "subtitleFontSize": 12,
        "subtitleColor": "#374151"
    },
    width=820,
    height=420
).configure_view(
    strokeWidth=0
).configure_axis(
    gridColor="#e5e7eb",
    labelFontSize=11,
    titleFontSize=12
).configure_legend(
    orient="top",
    title=None
)

grafico_region

,eleccion_id,anio,vuelta,region_codigo,region,region_fuente,division_regional,nulos,blancos,nulos_blancos,votos_emitidos,pct_nulos_blancos,nota_limite_regional,vuelta_label
92,2009_1,2009,1,15,Arica y Parinacota,ARICA Y PARINACOTA,15 regiones,3477,996,4473,82550,5.418534,División regional de 15 regiones: Biobío inclu...,Primera vuelta
122,2013_1,2013,1,15,Arica y Parinacota,ARICA Y PARINACOTA,15 regiones,700,371,1071,71188,1.504467,División regional de 15 regiones: Biobío inclu...,Primera vuelta
152,2017_1,2017,1,15,Arica y Parinacota,ARICA Y PARINACOTA,15 regiones,693,346,1039,74923,1.386757,División regional de 15 regiones: Biobío inclu...,Primera vuelta
182,2021_1,2021,1,15,Arica y Parinacota,Arica,16 regiones,756,332,1088,85884,1.266825,División regional de 16 regiones.,Primera vuelta
214,2025_1,2025,1,15,Arica y Parinacota,DE ARICA Y PARINACOTA,16 regiones,5037,1737,6774,157630,4.297405,División regional de 16 regiones.,Primera vuelta
107,2009_2,2009,2,15,Arica y Parinacota,ARICA Y PARINACOTA,15 regiones,3145,649,3794,80877,4.691074,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
137,2013_2,2013,2,15,Arica y Parinacota,ARICA Y PARINACOTA,15 regiones,862,306,1168,55582,2.101400,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
167,2017_2,2017,2,15,Arica y Parinacota,ARICA Y PARINACOTA,15 regiones,575,145,720,71216,1.011009,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
198,2021_2,2021,2,15,Arica y Parinacota,Arica,16 regiones,846,254,1100,88509,1.242811,División regional de 16 regiones.,Segunda vuelta
230,2025_2,2025,2,15,Arica y Parinacota,DE ARICA Y PARINACOTA,16 regiones,11563,1877,13440,157380,8.539840,División regional de 16 regiones.,Segunda vuelta

alt.Chart(...)

In [ ]:
region_elegida = "Ñuble"

datos_region = regional_grafico[
    regional_grafico["region"] == region_elegida
].copy()

display(datos_region)

grafico_region = alt.Chart(datos_region).mark_line(
    point=True,
    strokeWidth=3
).encode(
    x=alt.X(
        "anio:Q",
        title="Año",
        scale=alt.Scale(domain=[1989, 2025]),
        axis=alt.Axis(
            values=[1989, 1993, 1999, 2005, 2009, 2013, 2017, 2021, 2025],
            format="d",
            labelAngle=0
        )
    ),
    y=alt.Y(
        "pct_nulos_blancos:Q",
        title="% nulos + blancos",
        axis=alt.Axis(format=".1f")
    ),
    color=alt.Color(
        "vuelta_label:N",
        title=None,
        scale=alt.Scale(
            domain=["Primera vuelta", "Segunda vuelta"],
            range=["#64748b", "#d94841"]
        )
    ),
    detail="vuelta_label:N",
    tooltip=[
        alt.Tooltip("region:N", title="Región"),
        alt.Tooltip("anio:Q", title="Año", format="d"),
        alt.Tooltip("vuelta_label:N", title="Vuelta"),
        alt.Tooltip("pct_nulos_blancos:Q", title="% nulos + blancos", format=".2f"),
        alt.Tooltip("nulos_blancos:Q", title="Nulos + blancos", format=","),
        alt.Tooltip("votos_emitidos:Q", title="Votos emitidos", format=",")
    ]
).properties(
    title={
        "text": f"Evolución del voto nulo y blanco en {region_elegida}",
        "subtitle": "Porcentaje de votos nulos y blancos en elecciones presidenciales, 1989–2025",
        "anchor": "start",
        "fontSize": 18,
        "subtitleFontSize": 12,
        "subtitleColor": "#374151"
    },
    width=820,
    height=420
).configure_view(
    strokeWidth=0
).configure_axis(
    gridColor="#e5e7eb",
    labelFontSize=11,
    titleFontSize=12
).configure_legend(
    orient="top",
    title=None
)

grafico_region

,eleccion_id,anio,vuelta,region_codigo,region,region_fuente,division_regional,nulos,blancos,nulos_blancos,votos_emitidos,pct_nulos_blancos,nota_limite_regional,vuelta_label
183,2021_1,2021,1,16,Ñuble,Ñuble,16 regiones,1645,1250,2895,193860,1.493346,División regional de 16 regiones.,Primera vuelta
215,2025_1,2025,1,16,Ñuble,DE ÑUBLE,16 regiones,10049,4435,14484,406368,3.564257,División regional de 16 regiones.,Primera vuelta
199,2021_2,2021,2,16,Ñuble,Ñuble,16 regiones,1711,578,2289,235908,0.970294,División regional de 16 regiones.,Segunda vuelta
231,2025_2,2025,2,16,Ñuble,DE ÑUBLE,16 regiones,21161,4047,25208,405097,6.222707,División regional de 16 regiones.,Segunda vuelta

alt.Chart(...)

In [ ]:
region_elegida = "Aysén"

datos_region = regional_grafico[
    regional_grafico["region"] == region_elegida
].copy()

display(datos_region)

grafico_region = alt.Chart(datos_region).mark_line(
    point=True,
    strokeWidth=3
).encode(
    x=alt.X(
        "anio:Q",
        title="Año",
        scale=alt.Scale(domain=[1989, 2025]),
        axis=alt.Axis(
            values=[1989, 1993, 1999, 2005, 2009, 2013, 2017, 2021, 2025],
            format="d",
            labelAngle=0
        )
    ),
    y=alt.Y(
        "pct_nulos_blancos:Q",
        title="% nulos + blancos",
        axis=alt.Axis(format=".1f")
    ),
    color=alt.Color(
        "vuelta_label:N",
        title=None,
        scale=alt.Scale(
            domain=["Primera vuelta", "Segunda vuelta"],
            range=["#64748b", "#d94841"]
        )
    ),
    detail="vuelta_label:N",
    tooltip=[
        alt.Tooltip("region:N", title="Región"),
        alt.Tooltip("anio:Q", title="Año", format="d"),
        alt.Tooltip("vuelta_label:N", title="Vuelta"),
        alt.Tooltip("pct_nulos_blancos:Q", title="% nulos + blancos", format=".2f"),
        alt.Tooltip("nulos_blancos:Q", title="Nulos + blancos", format=","),
        alt.Tooltip("votos_emitidos:Q", title="Votos emitidos", format=",")
    ]
).properties(
    title={
        "text": f"Evolución del voto nulo y blanco en {region_elegida}",
        "subtitle": "Porcentaje de votos nulos y blancos en elecciones presidenciales, 1989–2025",
        "anchor": "start",
        "fontSize": 18,
        "subtitleFontSize": 12,
        "subtitleColor": "#374151"
    },
    width=820,
    height=420
).configure_view(
    strokeWidth=0
).configure_axis(
    gridColor="#e5e7eb",
    labelFontSize=11,
    titleFontSize=12
).configure_legend(
    orient="top",
    title=None
)

grafico_region

,eleccion_id,anio,vuelta,region_codigo,region,region_fuente,division_regional,nulos,blancos,nulos_blancos,votos_emitidos,pct_nulos_blancos,nota_limite_regional,vuelta_label
10,1989_1,1989,1,11,Aysén,Aysén,13 regiones,508,525,1033,38298,2.697269,División regional histórica de 13 regiones: Ta...,Primera vuelta
23,1993_1,1993,1,11,Aysén,Aysén,13 regiones,958,866,1824,41434,4.402182,División regional histórica de 13 regiones: Ta...,Primera vuelta
36,1999_1,1999,1,11,Aysén,AYSEN DEL GRAL. CARL,13 regiones,584,365,949,41883,2.265836,División regional histórica de 13 regiones: Ta...,Primera vuelta
62,2005_1,2005,1,11,Aysén,AISEN DEL GRAL. CARLOS IBAÐEZ,13 regiones,831,519,1350,42217,3.197764,División regional histórica de 13 regiones: Ta...,Primera vuelta
88,2009_1,2009,1,11,Aysén,AISEN DEL GRAL. CARLOS IBAÑEZ,15 regiones,855,576,1431,43734,3.272054,División regional de 15 regiones: Biobío inclu...,Primera vuelta
118,2013_1,2013,1,11,Aysén,AISEN DEL GRAL. CARLOS IBAÑEZ,15 regiones,294,311,605,37731,1.603456,División regional de 15 regiones: Biobío inclu...,Primera vuelta
148,2017_1,2017,1,11,Aysén,AISEN DEL GRAL. CARLOS IBAÑEZ,15 regiones,313,376,689,38105,1.808162,División regional de 15 regiones: Biobío inclu...,Primera vuelta
178,2021_1,2021,1,11,Aysén,Aysen,16 regiones,428,340,768,40677,1.888045,División regional de 16 regiones.,Primera vuelta
210,2025_1,2025,1,11,Aysén,DE AYSEN DEL GENERAL CARLOS IBAÑEZ DEL CAMPO,16 regiones,1909,1148,3057,72860,4.195718,División regional de 16 regiones.,Primera vuelta
49,1999_2,1999,2,11,Aysén,AYSEN DEL GRAL. CARL,13 regiones,425,242,667,42052,1.586131,División regional histórica de 13 regiones: Ta...,Segunda vuelta
75,2005_2,2005,2,11,Aysén,AISEN DEL GRAL. CARLOS IBAÐEZ,13 regiones,608,308,916,41184,2.224165,División regional histórica de 13 regiones: Ta...,Segunda vuelta
103,2009_2,2009,2,11,Aysén,AISEN DEL GRAL. CARLOS IBAÑEZ,15 regiones,938,331,1269,42588,2.979713,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
133,2013_2,2013,2,11,Aysén,AISEN DEL GRAL. CARLOS IBAÑEZ,15 regiones,389,144,533,32095,1.660695,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
163,2017_2,2017,2,11,Aysén,AISEN DEL GRAL. CARLOS IBAÑEZ,15 regiones,243,99,342,38039,0.899077,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
194,2021_2,2021,2,11,Aysén,Aysen,16 regiones,356,153,509,46490,1.094859,División regional de 16 regiones.,Segunda vuelta
226,2025_2,2025,2,11,Aysén,DE AYSEN DEL GENERAL CARLOS IBAÑEZ DEL CAMPO,16 regiones,3882,946,4828,72948,6.618413,División regional de 16 regiones.,Segunda vuelta

alt.Chart(...)

In [ ]:
region_elegida = "Magallanes"

datos_region = regional_grafico[
    regional_grafico["region"] == region_elegida
].copy()

display(datos_region)

grafico_region = alt.Chart(datos_region).mark_line(
    point=True,
    strokeWidth=3
).encode(
    x=alt.X(
        "anio:Q",
        title="Año",
        scale=alt.Scale(domain=[1989, 2025]),
        axis=alt.Axis(
            values=[1989, 1993, 1999, 2005, 2009, 2013, 2017, 2021, 2025],
            format="d",
            labelAngle=0
        )
    ),
    y=alt.Y(
        "pct_nulos_blancos:Q",
        title="% nulos + blancos",
        axis=alt.Axis(format=".1f")
    ),
    color=alt.Color(
        "vuelta_label:N",
        title=None,
        scale=alt.Scale(
            domain=["Primera vuelta", "Segunda vuelta"],
            range=["#64748b", "#d94841"]
        )
    ),
    detail="vuelta_label:N",
    tooltip=[
        alt.Tooltip("region:N", title="Región"),
        alt.Tooltip("anio:Q", title="Año", format="d"),
        alt.Tooltip("vuelta_label:N", title="Vuelta"),
        alt.Tooltip("pct_nulos_blancos:Q", title="% nulos + blancos", format=".2f"),
        alt.Tooltip("nulos_blancos:Q", title="Nulos + blancos", format=","),
        alt.Tooltip("votos_emitidos:Q", title="Votos emitidos", format=",")
    ]
).properties(
    title={
        "text": f"Evolución del voto nulo y blanco en {region_elegida}",
        "subtitle": "Porcentaje de votos nulos y blancos en elecciones presidenciales, 1989–2025",
        "anchor": "start",
        "fontSize": 18,
        "subtitleFontSize": 12,
        "subtitleColor": "#374151"
    },
    width=820,
    height=420
).configure_view(
    strokeWidth=0
).configure_axis(
    gridColor="#e5e7eb",
    labelFontSize=11,
    titleFontSize=12
).configure_legend(
    orient="top",
    title=None
)

grafico_region

,eleccion_id,anio,vuelta,region_codigo,region,region_fuente,division_regional,nulos,blancos,nulos_blancos,votos_emitidos,pct_nulos_blancos,nota_limite_regional,vuelta_label
11,1989_1,1989,1,12,Magallanes,Magallanes,13 regiones,874,634,1508,82521,1.827414,División regional histórica de 13 regiones: Ta...,Primera vuelta
24,1993_1,1993,1,12,Magallanes,Magallanes,13 regiones,3193,1237,4430,80450,5.506526,División regional histórica de 13 regiones: Ta...,Primera vuelta
37,1999_1,1999,1,12,Magallanes,DE MAGALLANES Y ANTA,13 regiones,1964,556,2520,76590,3.290247,División regional histórica de 13 regiones: Ta...,Primera vuelta
63,2005_1,2005,1,12,Magallanes,DE MAGALLANES Y ANTARTICA CH.,13 regiones,2023,866,2889,72234,3.999502,División regional histórica de 13 regiones: Ta...,Primera vuelta
89,2009_1,2009,1,12,Magallanes,DE MAGALLANES Y ANTARTICA CH.,15 regiones,1988,968,2956,72144,4.097361,División regional de 15 regiones: Biobío inclu...,Primera vuelta
119,2013_1,2013,1,12,Magallanes,DE MAGALLANES Y ANTARTICA CH.,15 regiones,462,348,810,62619,1.293537,División regional de 15 regiones: Biobío inclu...,Primera vuelta
149,2017_1,2017,1,12,Magallanes,DE MAGALLANES Y ANTARTICA CH.,15 regiones,527,243,770,61021,1.261861,División regional de 15 regiones: Biobío inclu...,Primera vuelta
179,2021_1,2021,1,12,Magallanes,Magallanes,16 regiones,648,304,952,70027,1.359476,División regional de 16 regiones.,Primera vuelta
211,2025_1,2025,1,12,Magallanes,DE MAGALLANES Y DE LA ANTARTICA CHILENA,16 regiones,4249,1770,6019,122394,4.917725,División regional de 16 regiones.,Primera vuelta
50,1999_2,1999,2,12,Magallanes,DE MAGALLANES Y ANTA,13 regiones,1197,381,1578,75229,2.097595,División regional histórica de 13 regiones: Ta...,Segunda vuelta
76,2005_2,2005,2,12,Magallanes,DE MAGALLANES Y ANTARTICA CH.,13 regiones,1662,423,2085,67814,3.074586,División regional histórica de 13 regiones: Ta...,Segunda vuelta
104,2009_2,2009,2,12,Magallanes,DE MAGALLANES Y ANTARTICA CH.,15 regiones,2255,681,2936,66969,4.384118,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
134,2013_2,2013,2,12,Magallanes,DE MAGALLANES Y ANTARTICA CH.,15 regiones,748,296,1044,50137,2.082295,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
164,2017_2,2017,2,12,Magallanes,DE MAGALLANES Y ANTARTICA CH.,15 regiones,509,152,661,60288,1.096404,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
195,2021_2,2021,2,12,Magallanes,Magallanes,16 regiones,696,188,884,78936,1.119895,División regional de 16 regiones.,Segunda vuelta
227,2025_2,2025,2,12,Magallanes,DE MAGALLANES Y DE LA ANTARTICA CHILENA,16 regiones,7686,1892,9578,121976,7.852364,División regional de 16 regiones.,Segunda vuelta

alt.Chart(...)

In [ ]:
heatmap_regional = regional_grafico.copy()

heatmap_regional["anio_vuelta"] = (
    heatmap_regional["anio"].astype(int).astype(str)
    + " "
    + heatmap_regional["vuelta"].astype(int).map({
        1: "1V",
        2: "2V"
    })
)

orden_anio_vuelta = (
    heatmap_regional
    .sort_values(["anio", "vuelta"])["anio_vuelta"]
    .drop_duplicates()
    .tolist()
)

display(heatmap_regional.head())

,eleccion_id,anio,vuelta,region_codigo,region,region_fuente,division_regional,nulos,blancos,nulos_blancos,votos_emitidos,pct_nulos_blancos,nota_limite_regional,vuelta_label,anio_vuelta
1,1989_1,1989,1,2,Antofagasta,Antofagasta,13 regiones,3191,1980,5171,214583,2.409790,División regional histórica de 13 regiones: Ta...,Primera vuelta,1989 1V
14,1993_1,1993,1,2,Antofagasta,Antofagasta,13 regiones,10375,3814,14189,216911,6.541393,División regional histórica de 13 regiones: Ta...,Primera vuelta,1993 1V
27,1999_1,1999,1,2,Antofagasta,DE ANTOFAGASTA,13 regiones,5835,1705,7540,206083,3.658720,División regional histórica de 13 regiones: Ta...,Primera vuelta,1999 1V
53,2005_1,2005,1,2,Antofagasta,DE ANTOFAGASTA,13 regiones,5705,2007,7712,202407,3.810145,División regional histórica de 13 regiones: Ta...,Primera vuelta,2005 1V
79,2009_1,2009,1,2,Antofagasta,DE ANTOFAGASTA,15 regiones,7259,2063,9322,198837,4.688262,División regional de 15 regiones: Biobío inclu...,Primera vuelta,2009 1V

In [ ]:
orden_regiones_norte_sur = [
    "Arica y Parinacota",
    "Tarapacá",
    "Antofagasta",
    "Atacama",
    "Coquimbo",
    "Valparaíso",
    "Metropolitana",
    "O’Higgins",
    "O'Higgins",
    "Maule",
    "Ñuble",
    "Biobío",
    "La Araucanía",
    "Los Ríos",
    "Los Lagos",
    "Aysén",
    "Magallanes"
]

grafico_heatmap_regional = alt.Chart(heatmap_regional).mark_rect().encode(
    x=alt.X(
        "anio_vuelta:N",
        title="Elección",
        sort=orden_anio_vuelta,
        axis=alt.Axis(labelAngle=-45)
    ),
    y=alt.Y(
        "region:N",
        title="Región",
        sort=orden_regiones_norte_sur
    ),
    color=alt.Color(
        "pct_nulos_blancos:Q",
        title="% nulos + blancos",
        scale=alt.Scale(scheme="reds")
    ),
    tooltip=[
        alt.Tooltip("region:N", title="Región"),
        alt.Tooltip("anio:Q", title="Año", format="d"),
        alt.Tooltip("vuelta_label:N", title="Vuelta"),
        alt.Tooltip("pct_nulos_blancos:Q", title="% nulos + blancos", format=".2f"),
        alt.Tooltip("nulos_blancos:Q", title="Nulos + blancos", format=","),
        alt.Tooltip("votos_emitidos:Q", title="Votos emitidos", format=",")
    ]
).properties(
    title={
        "text": "Dónde se concentra el voto nulo y blanco",
        "subtitle": "Porcentaje de votos nulos y blancos por región y elección presidencial, 1989–2025",
        "anchor": "start",
        "fontSize": 18,
        "subtitleFontSize": 12,
        "subtitleColor": "#374151"
    },
    width=900,
    height=460
).configure_view(
    strokeWidth=0
).configure_axis(
    labelFontSize=10,
    titleFontSize=12
).configure_legend(
    orient="right"
)

grafico_heatmap_regional

alt.Chart(...)

In [ ]:
ranking_2025 = regional_grafico[
    (regional_grafico["anio"] == 2025) &
    (regional_grafico["vuelta"] == 2)
].copy()

ranking_2025 = ranking_2025.sort_values("pct_nulos_blancos", ascending=False)

grafico_ranking_2025 = alt.Chart(ranking_2025).mark_bar(
    cornerRadiusEnd=4
).encode(
    x=alt.X(
        "pct_nulos_blancos:Q",
        title="% nulos + blancos",
        axis=alt.Axis(format=".1f")
    ),
    y=alt.Y(
        "region:N",
        title="Región",
        sort="-x"
    ),
    color=alt.Color(
        "pct_nulos_blancos:Q",
        title="% nulos + blancos",
        scale=alt.Scale(scheme="reds")
    ),
    tooltip=[
        alt.Tooltip("region:N", title="Región"),
        alt.Tooltip("pct_nulos_blancos:Q", title="% nulos + blancos", format=".2f"),
        alt.Tooltip("nulos_blancos:Q", title="Nulos + blancos", format=","),
        alt.Tooltip("votos_emitidos:Q", title="Votos emitidos", format=",")
    ]
).properties(
    title={
        "text": "Dónde pesó más el voto nulo y blanco en 2025",
        "subtitle": "Porcentaje regional de votos nulos y blancos en segunda vuelta presidencial",
        "anchor": "start",
        "fontSize": 18,
        "subtitleFontSize": 12,
        "subtitleColor": "#374151"
    },
    width=760,
    height=430
).configure_view(
    strokeWidth=0
).configure_axis(
    gridColor="#e5e7eb",
    labelFontSize=11,
    titleFontSize=12
).configure_legend(
    orient="right"
)

grafico_ranking_2025

alt.Chart(...)

In [ ]:
comparacion_2021_2025 = regional_grafico[
    (regional_grafico["anio"].isin([2021, 2025])) &
    (regional_grafico["vuelta"] == 2)
].copy()

tabla_cambio = comparacion_2021_2025.pivot_table(
    index="region",
    columns="anio",
    values="pct_nulos_blancos",
    aggfunc="first"
).reset_index()

tabla_cambio = tabla_cambio.rename(columns={
    2021: "pct_2021",
    2025: "pct_2025"
})

tabla_cambio = tabla_cambio.dropna(subset=["pct_2021", "pct_2025"])

tabla_cambio["cambio_pp"] = tabla_cambio["pct_2025"] - tabla_cambio["pct_2021"]

tabla_cambio["direccion"] = np.where(
    tabla_cambio["cambio_pp"] >= 0,
    "Sube",
    "Baja"
)

tabla_cambio = tabla_cambio.sort_values("cambio_pp", ascending=False)

display(tabla_cambio)

anio              region  pct_2021   pct_2025  cambio_pp direccion
0            Antofagasta  1.448995  10.481805   9.032810      Sube
2                Atacama  1.093309   9.505282   8.411973      Sube
5               Coquimbo  1.139721   8.820353   7.680632      Sube
1     Arica y Parinacota  1.242811   8.539840   7.297029      Sube
13              Tarapacá  1.245245   8.175522   6.930277      Sube
9             Magallanes  1.119895   7.852364   6.732469      Sube
14            Valparaíso  1.097160   7.709124   6.611964      Sube
4                 Biobío  1.159516   7.633771   6.474255      Sube
12             O’Higgins  0.964397   7.365685   6.401288      Sube
7              Los Lagos  1.108501   7.341939   6.233438      Sube
10                 Maule  0.972638   6.649530   5.676892      Sube
3                  Aysén  1.094859   6.618413   5.523554      Sube
8               Los Ríos  1.060123   6.488430   5.428307      Sube
15                 Ñuble  0.970294   6.222707   5.252413      Sube
11         Metropolitana  1.120524   6.344915   5.224391      Sube
6           La Araucanía  1.056980   6.269424   5.212444      Sube

In [ ]:
grafico_cambio_2021_2025 = alt.Chart(tabla_cambio).mark_bar(
    cornerRadiusEnd=4
).encode(
    x=alt.X(
        "cambio_pp:Q",
        title="Cambio en puntos porcentuales",
        axis=alt.Axis(format="+.1f")
    ),
    y=alt.Y(
        "region:N",
        title="Región",
        sort="-x"
    ),
    color=alt.Color(
        "direccion:N",
        title=None,
        scale=alt.Scale(
            domain=["Sube", "Baja"],
            range=["#d94841", "#64748b"]
        )
    ),
    tooltip=[
        alt.Tooltip("region:N", title="Región"),
        alt.Tooltip("pct_2021:Q", title="2021 segunda vuelta", format=".2f"),
        alt.Tooltip("pct_2025:Q", title="2025 segunda vuelta", format=".2f"),
        alt.Tooltip("cambio_pp:Q", title="Cambio pp", format="+.2f")
    ]
).properties(
    title={
        "text": "Dónde cambió más el voto nulo y blanco entre 2021 y 2025",
        "subtitle": "Diferencia regional en puntos porcentuales, segunda vuelta presidencial",
        "anchor": "start",
        "fontSize": 18,
        "subtitleFontSize": 12,
        "subtitleColor": "#374151"
    },
    width=760,
    height=430
).configure_view(
    strokeWidth=0
).configure_axis(
    gridColor="#e5e7eb",
    labelFontSize=11,
    titleFontSize=12
).configure_legend(
    orient="top",
    title=None
)

grafico_cambio_2021_2025

alt.Chart(...)

In [ ]:
mapa_chile_2025 = regional_grafico[
    (regional_grafico["anio"] == 2025) &
    (regional_grafico["vuelta"] == 2)
].copy()

orden_chile = pd.DataFrame({
    "region": [
        "Arica y Parinacota",
        "Tarapacá",
        "Antofagasta",
        "Atacama",
        "Coquimbo",
        "Valparaíso",
        "Metropolitana",
        "O'Higgins",
        "Maule",
        "Ñuble",
        "Biobío",
        "La Araucanía",
        "Los Ríos",
        "Los Lagos",
        "Aysén",
        "Magallanes"
    ],
    "posicion": list(range(16, 0, -1)),
    "x": [
        1.2, 1.1, 1.0, 1.1,
        1.2, 1.3, 1.35, 1.25,
        1.15, 1.1, 1.05, 1.0,
        0.95, 0.9, 0.85, 0.8
    ]
})

mapa_chile_2025 = mapa_chile_2025.merge(
    orden_chile,
    on="region",
    how="left"
)

display(mapa_chile_2025)

,eleccion_id,anio,vuelta,region_codigo,region,region_fuente,division_regional,nulos,blancos,nulos_blancos,votos_emitidos,pct_nulos_blancos,nota_limite_regional,vuelta_label,posicion,x
0,2025_2,2025,2,2,Antofagasta,DE ANTOFAGASTA,16 regiones,36870,5853,42723,407592,10.481805,División regional de 16 regiones.,Segunda vuelta,14.0,1.00
1,2025_2,2025,2,15,Arica y Parinacota,DE ARICA Y PARINACOTA,16 regiones,11563,1877,13440,157380,8.539840,División regional de 16 regiones.,Segunda vuelta,16.0,1.20
2,2025_2,2025,2,3,Atacama,DE ATACAMA,16 regiones,16879,3080,19959,209978,9.505282,División regional de 16 regiones.,Segunda vuelta,13.0,1.10
3,2025_2,2025,2,11,Aysén,DE AYSEN DEL GENERAL CARLOS IBAÑEZ DEL CAMPO,16 regiones,3882,946,4828,72948,6.618413,División regional de 16 regiones.,Segunda vuelta,2.0,0.85
4,2025_2,2025,2,8,Biobío,DEL BIOBIO,16 regiones,77428,15363,92791,1215533,7.633771,División regional de 16 regiones.,Segunda vuelta,6.0,1.05
5,2025_2,2025,2,4,Coquimbo,DE COQUIMBO,16 regiones,42661,8795,51456,583378,8.820353,División regional de 16 regiones.,Segunda vuelta,12.0,1.20
6,2025_2,2025,2,9,La Araucanía,DE LA ARAUCANIA,16 regiones,40303,8394,48697,776738,6.269424,División regional de 16 regiones.,Segunda vuelta,5.0,1.00
7,2025_2,2025,2,10,Los Lagos,DE LOS LAGOS,16 regiones,40351,8993,49344,672084,7.341939,División regional de 16 regiones.,Segunda vuelta,3.0,0.90
8,2025_2,2025,2,14,Los Ríos,DE LOS RIOS,16 regiones,16628,3673,20301,312880,6.488430,División regional de 16 regiones.,Segunda vuelta,4.0,0.95
9,2025_2,2025,2,12,Magallanes,DE MAGALLANES Y DE LA ANTARTICA CHILENA,16 regiones,7686,1892,9578,121976,7.852364,División regional de 16 regiones.,Segunda vuelta,1.0,0.80
10,2025_2,2025,2,7,Maule,DEL MAULE,16 regiones,48586,8662,57248,860933,6.649530,División regional de 16 regiones.,Segunda vuelta,8.0,1.15
11,2025_2,2025,2,13,Metropolitana,METROPOLITANA DE SANTIAGO,16 regiones,264943,62460,327403,5160085,6.344915,División regional de 16 regiones.,Segunda vuelta,10.0,1.35
12,2025_2,2025,2,6,O’Higgins,DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS,16 regiones,46289,9511,55800,757567,7.365685,División regional de 16 regiones.,Segunda vuelta,NaN,NaN
13,2025_2,2025,2,1,Tarapacá,DE TARAPACA,16 regiones,14813,2529,17342,212121,8.175522,División regional de 16 regiones.,Segunda vuelta,15.0,1.10
14,2025_2,2025,2,5,Valparaíso,DE VALPARAISO,16 regiones,92800,18917,111717,1449153,7.709124,División regional de 16 regiones.,Segunda vuelta,11.0,1.30
15,2025_2,2025,2,16,Ñuble,DE ÑUBLE,16 regiones,21161,4047,25208,405097,6.222707,División regional de 16 regiones.,Segunda vuelta,7.0,1.10

In [ ]:
grafico_mapa_chile_2025 = alt.Chart(mapa_chile_2025).mark_rect(
    width=42,
    height=26,
    cornerRadius=4
).encode(
    x=alt.X(
        "x:Q",
        title=None,
        axis=None,
        scale=alt.Scale(domain=[0.5, 1.7])
    ),
    y=alt.Y(
        "posicion:Q",
        title=None,
        axis=None,
        scale=alt.Scale(domain=[0.5, 16.7])
    ),
    color=alt.Color(
        "pct_nulos_blancos:Q",
        title="% nulos + blancos",
        scale=alt.Scale(scheme="reds")
    ),
    tooltip=[
        alt.Tooltip("region:N", title="Región"),
        alt.Tooltip("pct_nulos_blancos:Q", title="% nulos + blancos", format=".2f"),
        alt.Tooltip("nulos_blancos:Q", title="Nulos + blancos", format=","),
        alt.Tooltip("votos_emitidos:Q", title="Votos emitidos", format=",")
    ]
)

etiquetas_mapa = alt.Chart(mapa_chile_2025).mark_text(
    align="left",
    dx=28,
    fontSize=11
).encode(
    x=alt.X("x:Q"),
    y=alt.Y("posicion:Q"),
    text="region:N"
)

grafico_mapa_chile_2025 = (grafico_mapa_chile_2025 + etiquetas_mapa).properties(
    title={
        "text": "El voto nulo y blanco en el territorio",
        "subtitle": "Porcentaje regional de votos nulos y blancos en segunda vuelta presidencial 2025",
        "anchor": "start",
        "fontSize": 18,
        "subtitleFontSize": 12,
        "subtitleColor": "#374151"
    },
    width=430,
    height=620
).configure_view(
    strokeWidth=0
).configure_legend(
    orient="right"
)

grafico_mapa_chile_2025

alt.LayerChart(...)

In [ ]:
mapa_chile_todos = regional_grafico.copy()

# Normalizamos apóstrofe por si O'Higgins viene con apóstrofe curvo
mapa_chile_todos["region_mapa"] = (
    mapa_chile_todos["region"]
    .astype(str)
    .str.replace("’", "'", regex=False)
)

mapa_chile_todos["anio_vuelta"] = (
    mapa_chile_todos["anio"].astype(int).astype(str)
    + " "
    + mapa_chile_todos["vuelta"].astype(int).map({
        1: "1V",
        2: "2V"
    })
)

orden_anio_vuelta = (
    mapa_chile_todos
    .sort_values(["anio", "vuelta"])["anio_vuelta"]
    .drop_duplicates()
    .tolist()
)

orden_chile = pd.DataFrame({
    "region_mapa": [
        "Arica y Parinacota",
        "Tarapacá",
        "Antofagasta",
        "Atacama",
        "Coquimbo",
        "Valparaíso",
        "Metropolitana",
        "O'Higgins",
        "Maule",
        "Ñuble",
        "Biobío",
        "La Araucanía",
        "Los Ríos",
        "Los Lagos",
        "Aysén",
        "Magallanes"
    ],
    "posicion": list(range(16, 0, -1)),
    "x": [
        1.2, 1.1, 1.0, 1.1,
        1.2, 1.3, 1.35, 1.25,
        1.15, 1.1, 1.05, 1.0,
        0.95, 0.9, 0.85, 0.8
    ]
})

mapa_chile_todos = mapa_chile_todos.merge(
    orden_chile,
    on="region_mapa",
    how="left"
)

display(mapa_chile_todos.head())
print(mapa_chile_todos.shape)

,eleccion_id,anio,vuelta,region_codigo,region,region_fuente,division_regional,nulos,blancos,nulos_blancos,votos_emitidos,pct_nulos_blancos,nota_limite_regional,vuelta_label,region_mapa,anio_vuelta,posicion,x
0,1989_1,1989,1,2,Antofagasta,Antofagasta,13 regiones,3191,1980,5171,214583,2.409790,División regional histórica de 13 regiones: Ta...,Primera vuelta,Antofagasta,1989 1V,14,1.0
1,1993_1,1993,1,2,Antofagasta,Antofagasta,13 regiones,10375,3814,14189,216911,6.541393,División regional histórica de 13 regiones: Ta...,Primera vuelta,Antofagasta,1993 1V,14,1.0
2,1999_1,1999,1,2,Antofagasta,DE ANTOFAGASTA,13 regiones,5835,1705,7540,206083,3.658720,División regional histórica de 13 regiones: Ta...,Primera vuelta,Antofagasta,1999 1V,14,1.0
3,2005_1,2005,1,2,Antofagasta,DE ANTOFAGASTA,13 regiones,5705,2007,7712,202407,3.810145,División regional histórica de 13 regiones: Ta...,Primera vuelta,Antofagasta,2005 1V,14,1.0
4,2009_1,2009,1,2,Antofagasta,DE ANTOFAGASTA,15 regiones,7259,2063,9322,198837,4.688262,División regional de 15 regiones: Biobío inclu...,Primera vuelta,Antofagasta,2009 1V,14,1.0

(232, 18)

In [ ]:
grafico_mapa_chile_todos = alt.Chart(mapa_chile_todos, width=120, height=210).mark_rect(
    width=18,
    height=10,
    cornerRadius=2
).encode(
    x=alt.X(
        "x:Q",
        title=None,
        axis=None,
        scale=alt.Scale(domain=[0.5, 1.7])
    ),
    y=alt.Y(
        "posicion:Q",
        title=None,
        axis=None,
        scale=alt.Scale(domain=[0.5, 16.7])
    ),
    color=alt.Color(
        "pct_nulos_blancos:Q",
        title="% nulos + blancos",
        scale=alt.Scale(scheme="reds")
    ),
    tooltip=[
        alt.Tooltip("region:N", title="Región"),
        alt.Tooltip("anio:Q", title="Año", format="d"),
        alt.Tooltip("vuelta_label:N", title="Vuelta"),
        alt.Tooltip("pct_nulos_blancos:Q", title="% nulos + blancos", format=".2f"),
        alt.Tooltip("nulos_blancos:Q", title="Nulos + blancos", format=","),
        alt.Tooltip("votos_emitidos:Q", title="Votos emitidos", format=",")
    ]
).facet(
    facet=alt.Facet("anio_vuelta:N", sort=orden_anio_vuelta),
    title=None,
    columns=4
).properties(
    title={
        "text": "El voto nulo y blanco visto como territorio",
        "subtitle": "Cartograma tipo Chile por región y elección presidencial, 1989–2025",
        "anchor": "start",
        "fontSize": 18,
        "subtitleFontSize": 12,
        "subtitleColor": "#374151"
    }
).configure_view(
    strokeWidth=0
).configure_header(
    labelFontSize=11,
    labelFontWeight="bold"
).configure_legend(
    orient="right"
)

grafico_mapa_chile_todos

alt.FacetChart(...)

In [ ]:
datos_region = regional_grafico[
    regional_grafico["region"].astype(str).str.contains("Higgins", case=False, na=False)
].copy()

region_elegida = datos_region["region"].iloc[0]

display(datos_region)

grafico_region = alt.Chart(datos_region).mark_line(
    point=True,
    strokeWidth=3
).encode(
    x=alt.X(
        "anio:Q",
        title="Año",
        scale=alt.Scale(domain=[1989, 2025]),
        axis=alt.Axis(
            values=[1989, 1993, 1999, 2005, 2009, 2013, 2017, 2021, 2025],
            format="d",
            labelAngle=0
        )
    ),
    y=alt.Y(
        "pct_nulos_blancos:Q",
        title="% nulos + blancos",
        axis=alt.Axis(format=".1f")
    ),
    color=alt.Color(
        "vuelta_label:N",
        title=None,
        scale=alt.Scale(
            domain=["Primera vuelta", "Segunda vuelta"],
            range=["#64748b", "#d94841"]
        )
    ),
    detail="vuelta_label:N",
    tooltip=[
        alt.Tooltip("region:N", title="Región"),
        alt.Tooltip("anio:Q", title="Año", format="d"),
        alt.Tooltip("vuelta_label:N", title="Vuelta"),
        alt.Tooltip("pct_nulos_blancos:Q", title="% nulos + blancos", format=".2f"),
        alt.Tooltip("nulos_blancos:Q", title="Nulos + blancos", format=","),
        alt.Tooltip("votos_emitidos:Q", title="Votos emitidos", format=",")
    ]
).properties(
    title={
        "text": f"Evolución del voto nulo y blanco en {region_elegida}",
        "subtitle": "Porcentaje de votos nulos y blancos en elecciones presidenciales, 1989–2025",
        "anchor": "start",
        "fontSize": 18,
        "subtitleFontSize": 12,
        "subtitleColor": "#374151"
    },
    width=820,
    height=420
).configure_view(
    strokeWidth=0
).configure_axis(
    gridColor="#e5e7eb",
    labelFontSize=11,
    titleFontSize=12
).configure_legend(
    orient="top",
    title=None
)

grafico_region

,eleccion_id,anio,vuelta,region_codigo,region,region_fuente,division_regional,nulos,blancos,nulos_blancos,votos_emitidos,pct_nulos_blancos,nota_limite_regional,vuelta_label
5,1989_1,1989,1,6,O’Higgins,O’Higgins,13 regiones,5174,4996,10170,378342,2.688044,División regional histórica de 13 regiones: Ta...,Primera vuelta
18,1993_1,1993,1,6,O’Higgins,O’Higgins,13 regiones,14052,8869,22921,404192,5.670820,División regional histórica de 13 regiones: Ta...,Primera vuelta
31,1999_1,1999,1,6,O’Higgins,DEL LIBERTADOR BDO.,13 regiones,8337,3581,11918,404217,2.948416,División regional histórica de 13 regiones: Ta...,Primera vuelta
57,2005_1,2005,1,6,O’Higgins,DEL LIBERTADOR BDO. O'HIGGINS,13 regiones,9984,5936,15920,407474,3.906998,División regional histórica de 13 regiones: Ta...,Primera vuelta
83,2009_1,2009,1,6,O’Higgins,DEL LIBERTADOR BDO. OHIGGINS,15 regiones,10362,5377,15739,414661,3.795631,División regional de 15 regiones: Biobío inclu...,Primera vuelta
113,2013_1,2013,1,6,O’Higgins,DEL LIBERTADOR BDO. O'HIGGINS,15 regiones,3560,2723,6283,366505,1.714301,División regional de 15 regiones: Biobío inclu...,Primera vuelta
143,2017_1,2017,1,6,O’Higgins,DEL LIBERTADOR BDO. O'HIGGINS,15 regiones,3315,2399,5714,353867,1.614731,División regional de 15 regiones: Biobío inclu...,Primera vuelta
173,2021_1,2021,1,6,O’Higgins,Libertador,16 regiones,3187,2094,5281,368873,1.431658,División regional de 16 regiones.,Primera vuelta
205,2025_1,2025,1,6,O’Higgins,DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS,16 regiones,21593,8397,29990,759407,3.949134,División regional de 16 regiones.,Primera vuelta
44,1999_2,1999,2,6,O’Higgins,DEL LIBERTADOR BDO.,13 regiones,5109,2576,7685,407092,1.887780,División regional histórica de 13 regiones: Ta...,Segunda vuelta
70,2005_2,2005,2,6,O’Higgins,DEL LIBERTADOR BDO. O'HIGGINS,13 regiones,8282,2856,11138,406534,2.739746,División regional histórica de 13 regiones: Ta...,Segunda vuelta
98,2009_2,2009,2,6,O’Higgins,DEL LIBERTADOR BDO. O'HIGGINS,15 regiones,9479,3023,12502,413240,3.025361,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
128,2013_2,2013,2,6,O’Higgins,DEL LIBERTADOR BDO. O'HIGGINS,15 regiones,3523,1405,4928,321995,1.530459,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
158,2017_2,2017,2,6,O’Higgins,DEL LIBERTADOR BDO. O'HIGGINS,15 regiones,2570,886,3456,381915,0.904913,División regional de 15 regiones: Biobío inclu...,Segunda vuelta
189,2021_2,2021,2,6,O’Higgins,Libertador,16 regiones,3174,1099,4273,443075,0.964397,División regional de 16 regiones.,Segunda vuelta
221,2025_2,2025,2,6,O’Higgins,DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS,16 regiones,46289,9511,55800,757567,7.365685,División regional de 16 regiones.,Segunda vuelta

alt.Chart(...)

In [ ]:
import os
import shutil
import unicodedata

os.makedirs("graficos_html", exist_ok=True)

# -----------------------------
# 1. GUARDAR GRÁFICOS PRINCIPALES
# -----------------------------

graficos_principales = {
    "01_evolucion_nacional_nulos_blancos.html": grafico_1,
    "02_diferencia_primera_segunda_vuelta.html": grafico_2,
    "03_sistema_electoral_nulos_blancos.html": grafico_3,
    "05_polarizacion_oferta_presidencial.html": grafico_5,
    "07_heatmap_regional_nulos_blancos.html": grafico_heatmap_regional,
    "08_ranking_regional_2025_nulos_blancos.html": grafico_ranking_2025,
    "11_mapa_calor_chile_2025_nulos_blancos.html": grafico_mapa_chile_2025,
    "12_cartograma_chile_todos_los_anios_nulos_blancos.html": grafico_mapa_chile_todos
}

for nombre_archivo, grafico in graficos_principales.items():
    grafico.save(f"graficos_html/{nombre_archivo}")
    print("Guardado:", nombre_archivo)


# -----------------------------
# 2. FUNCIÓN PARA NOMBRAR REGIONES
# -----------------------------

def limpiar_nombre_region(nombre):
    nombre = str(nombre).lower()
    nombre = nombre.replace("ñ", "n")
    nombre = nombre.replace("’", "")
    nombre = nombre.replace("'", "")
    nombre = unicodedata.normalize("NFKD", nombre)
    nombre = "".join(c for c in nombre if not unicodedata.combining(c))
    nombre = nombre.replace(" ", "_")
    return nombre


# -----------------------------
# 3. GUARDAR GRÁFICOS REGIONALES
# -----------------------------

regiones = sorted(regional_grafico["region"].dropna().unique())

for region_elegida in regiones:
    datos_region = regional_grafico[
        regional_grafico["region"] == region_elegida
    ].copy()

    grafico_region = alt.Chart(datos_region).mark_line(
        point=True,
        strokeWidth=3
    ).encode(
        x=alt.X(
            "anio:Q",
            title="Año",
            scale=alt.Scale(domain=[1989, 2025]),
            axis=alt.Axis(
                values=[1989, 1993, 1999, 2005, 2009, 2013, 2017, 2021, 2025],
                format="d",
                labelAngle=0
            )
        ),
        y=alt.Y(
            "pct_nulos_blancos:Q",
            title="% nulos + blancos",
            axis=alt.Axis(format=".1f")
        ),
        color=alt.Color(
            "vuelta_label:N",
            title=None,
            scale=alt.Scale(
                domain=["Primera vuelta", "Segunda vuelta"],
                range=["#64748b", "#d94841"]
            )
        ),
        detail="vuelta_label:N",
        tooltip=[
            alt.Tooltip("region:N", title="Región"),
            alt.Tooltip("anio:Q", title="Año", format="d"),
            alt.Tooltip("vuelta_label:N", title="Vuelta"),
            alt.Tooltip("pct_nulos_blancos:Q", title="% nulos + blancos", format=".2f"),
            alt.Tooltip("nulos_blancos:Q", title="Nulos + blancos", format=","),
            alt.Tooltip("votos_emitidos:Q", title="Votos emitidos", format=",")
        ]
    ).properties(
        title={
            "text": f"Evolución del voto nulo y blanco en {region_elegida}",
            "subtitle": "Porcentaje de votos nulos y blancos en elecciones presidenciales, 1989–2025",
            "anchor": "start",
            "fontSize": 18,
            "subtitleFontSize": 12,
            "subtitleColor": "#374151"
        },
        width=820,
        height=420
    ).configure_view(
        strokeWidth=0
    ).configure_axis(
        gridColor="#e5e7eb",
        labelFontSize=11,
        titleFontSize=12
    ).configure_legend(
        orient="top",
        title=None
    )

    nombre_archivo = "region_" + limpiar_nombre_region(region_elegida) + ".html"
    grafico_region.save(f"graficos_html/{nombre_archivo}")
    print("Guardado:", nombre_archivo)


# -----------------------------
# 4. CREAR ZIP FINAL
# -----------------------------

shutil.make_archive("graficos_html", "zip", "graficos_html")

print("LISTO: se creó graficos_html.zip")
print("Descarga graficos_html.zip desde el panel izquierdo de Colab.")

Guardado: 01_evolucion_nacional_nulos_blancos.html
Guardado: 02_diferencia_primera_segunda_vuelta.html
Guardado: 03_sistema_electoral_nulos_blancos.html
Guardado: 05_polarizacion_oferta_presidencial.html
Guardado: 07_heatmap_regional_nulos_blancos.html
Guardado: 08_ranking_regional_2025_nulos_blancos.html
Guardado: 11_mapa_calor_chile_2025_nulos_blancos.html
Guardado: 12_cartograma_chile_todos_los_anios_nulos_blancos.html
Guardado: region_antofagasta.html
Guardado: region_arica_y_parinacota.html
Guardado: region_atacama.html
Guardado: region_aysen.html
Guardado: region_biobio.html
Guardado: region_coquimbo.html
Guardado: region_la_araucania.html
Guardado: region_los_lagos.html
Guardado: region_los_rios.html
Guardado: region_magallanes.html
Guardado: region_maule.html
Guardado: region_metropolitana.html
Guardado: region_ohiggins.html
Guardado: region_tarapaca.html
Guardado: region_valparaiso.html
Guardado: region_nuble.html
LISTO: se creó graficos_html.zip
Descarga graficos_html.zip desde el panel izquierdo de Colab.