In [22]:
from google.colab import files
uploaded = files.upload()

Saving Base de Datos Vicente Soza.csv to Base de Datos Vicente Soza (5).csv

In [23]:
import pandas as pd

In [24]:
df = pd.read_csv("Base de Datos Vicente Soza.csv")

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 1: invalid continuation byte

In [25]:
import pandas as pd

df = pd.read_csv("Base de Datos Vicente Soza.csv", encoding="latin1")
df.head()

,Año,Arica y Parinacota votos,Arica y Parinacota Nulos y Blancos,Tarapacá votos,Tarapacá Nulos y Blancos,Antofagasta votos,Antofagasta Nulos y Blancos,Atacama Votos,Atacama Nulos y Blancos,Coquimbo Votos,...,Los Ríos Votos,Los Ríos Nulos y Blancos,Los Lagos Votos,Los Lagos Nulos y Blancos,Aysén Votos,Aysén Nulos y Blancos,Magallanes Votos,Magallanes Nulos y Blancos,Total Votos,Total Nulos
0,1989,NaN,NaN,170.476,4.572,214.583,5.171,114.639,2.886,254.929,...,NaN,NaN,488.347,14.450,38.298,1.033,82.521,1.508,7.158.727,178.868
1,1993,NaN,NaN,176.663,"10,110",216.911,14.189,120.020,"6,830",268.842,...,NaN,NaN,508.816,29.376,41.434,1.824,"80,450","4,430",7.383.286,408.339
2,1999,NaN,NaN,178.254,4.696,204.922,5.083,115.706,2.463,274.687,...,NaN,NaN,514.550,8.418,42.052,667.000,75.229,1.578,7.326.753,148.026
3,2005,NaN,NaN,177.018,5.997,195.784,6.406,113.415,3.482,275.454,...,NaN,NaN,512.786,12.285,41.184,916.000,67.814,2.085,7.162.345,202.932
4,2009,80.877,3.794,97.719,4.186,190.514,9.084,113.204,4.239,277.634,...,174.998,4.945,347.338,10.066,42.588,1.269,66.969,2.936,7.203.371,244.399

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 35 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Año                                 9 non-null      int64
 1   Arica y Parinacota votos            5 non-null      float64
 2   Arica y Parinacota Nulos y Blancos  5 non-null      object
 3   Tarapacá votos                      9 non-null      float64
 4   Tarapacá Nulos y Blancos            9 non-null      object
 5   Antofagasta votos                   9 non-null      float64
 6   Antofagasta Nulos y Blancos         9 non-null      float64
 7   Atacama Votos                       9 non-null      float64
 8   Atacama Nulos y Blancos             9 non-null      object
 9   Coquimbo Votos                      9 non-null      float64
 10  Coquimbo Nulos y Blancos            9 non-null      object
 11  Valparaíso Votos                    9 non-null      object
 12  Valparaíso Nulos y Blancos          9 non-null      float64
 13  Metropolitana Votos                 9 non-null      object
 14  Metropolitana Nulos y Blancos       9 non-null      float64
 15  O'Higgnins Votos                    9 non-null      float64
 16  O`Higgnis Nulos Y blancos           9 non-null      float64
 17  Maule Votos                         9 non-null      float64
 18  Maule Nulos y Blancos               9 non-null      object
 19  Ñuble Votos                         2 non-null      float64
 20  Ñuble Nulos y Blancos               2 non-null      float64
 21  Biobío Votos                        9 non-null      object
 22  Biobío Nulos y Blancos              9 non-null      object
 23  Araucanía Votos                     9 non-null      float64
 24  Araucanía Nulos y Blancos           9 non-null      object
 25  Los Ríos Votos                      5 non-null      float64
 26  Los Ríos Nulos y Blancos            5 non-null      float64
 27  Los Lagos Votos                     9 non-null      float64
 28  Los Lagos Nulos y Blancos           9 non-null      float64
 29  Aysén Votos                         9 non-null      float64
 30  Aysén Nulos y Blancos               9 non-null      float64
 31  Magallanes Votos                    9 non-null      object
 32  Magallanes Nulos y Blancos          9 non-null      object
 33  Total Votos                         9 non-null      object
 34  Total Nulos                         9 non-null      float64
dtypes: float64(21), int64(1), object(13)
memory usage: 2.6+ KB

In [29]:
df.describe()

,Año,Arica y Parinacota votos,Tarapacá votos,Antofagasta votos,Antofagasta Nulos y Blancos,Atacama Votos,Coquimbo Votos,Valparaíso Nulos y Blancos,Metropolitana Nulos y Blancos,O'Higgnins Votos,...,Ñuble Votos,Ñuble Nulos y Blancos,Araucanía Votos,Los Ríos Votos,Los Ríos Nulos y Blancos,Los Lagos Votos,Los Lagos Nulos y Blancos,Aysén Votos,Aysén Nulos y Blancos,Total Nulos
count,9.000000,5.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,...,2.000000,2.000000,9.000000,5.000000,5.000000,9.000000,9.000000,9.000000,9.000000,9.000000
mean,2007.888889,90.724000,142.918222,217.880556,10.085000,120.871333,304.886333,31.387667,99.863333,434.871778,...,319.801000,4.210500,453.862333,196.242600,6.264000,447.527444,15.084556,43.901667,330.660222,268.257889
std,12.454361,39.267935,50.475167,75.853858,12.781214,35.449019,107.241645,32.247903,92.003127,125.427385,...,118.642618,2.717411,125.316937,67.985805,7.972475,124.509669,15.080234,11.583530,346.425056,274.057526
min,1989.000000,55.582000,65.299000,131.326000,1.987000,80.579000,223.985000,8.084000,33.507000,321.995000,...,235.908000,2.289000,340.178000,138.160000,1.726000,271.558000,3.286000,32.095000,1.033000,75.332000
25%,1999.000000,71.216000,97.719000,190.514000,3.148000,113.204000,266.673000,13.458000,53.144000,381.915000,...,277.854500,3.249750,408.498000,164.306000,2.023000,347.338000,4.345000,38.298000,1.824000,115.481000
50%,2009.000000,80.877000,170.476000,204.922000,5.171000,114.639000,274.687000,19.251000,59.528000,406.534000,...,319.801000,4.210500,420.757000,174.998000,2.287000,488.347000,10.066000,41.434000,342.000000,178.868000
75%,2017.000000,88.509000,177.018000,216.911000,9.084000,117.716000,277.634000,30.278000,100.053000,413.240000,...,361.747500,5.171250,424.151000,190.827000,4.945000,512.786000,14.450000,42.588000,533.000000,244.399000
max,2025.000000,157.436000,212.112000,407.251000,42.683000,209.813000,583.274000,111.624000,327.030000,757.461000,...,403.694000,6.132000,776.378000,312.922000,20.339000,671.660000,49.236000,72.935000,916.000000,948.356000

In [30]:
print("Primeras filas de la base de datos:")
df.head()

Primeras filas de la base de datos:

,Año,Arica y Parinacota votos,Arica y Parinacota Nulos y Blancos,Tarapacá votos,Tarapacá Nulos y Blancos,Antofagasta votos,Antofagasta Nulos y Blancos,Atacama Votos,Atacama Nulos y Blancos,Coquimbo Votos,...,Los Ríos Votos,Los Ríos Nulos y Blancos,Los Lagos Votos,Los Lagos Nulos y Blancos,Aysén Votos,Aysén Nulos y Blancos,Magallanes Votos,Magallanes Nulos y Blancos,Total Votos,Total Nulos
0,1989,NaN,NaN,170.476,4.572,214.583,5.171,114.639,2.886,254.929,...,NaN,NaN,488.347,14.450,38.298,1.033,82.521,1.508,7.158.727,178.868
1,1993,NaN,NaN,176.663,"10,110",216.911,14.189,120.020,"6,830",268.842,...,NaN,NaN,508.816,29.376,41.434,1.824,"80,450","4,430",7.383.286,408.339
2,1999,NaN,NaN,178.254,4.696,204.922,5.083,115.706,2.463,274.687,...,NaN,NaN,514.550,8.418,42.052,667.000,75.229,1.578,7.326.753,148.026
3,2005,NaN,NaN,177.018,5.997,195.784,6.406,113.415,3.482,275.454,...,NaN,NaN,512.786,12.285,41.184,916.000,67.814,2.085,7.162.345,202.932
4,2009,80.877,3.794,97.719,4.186,190.514,9.084,113.204,4.239,277.634,...,174.998,4.945,347.338,10.066,42.588,1.269,66.969,2.936,7.203.371,244.399